project -new
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_rsp_mux.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_arbitrator.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_rsp_demux.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_cmd_mux.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_cmd_demux.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_burst_adapter.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_burst_adapter_uncmpr.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_burst_adapter_13_1.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_burst_adapter_new.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_incr_burst_converter.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_wrap_burst_converter.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_default_burst_converter.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_address_alignment.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_avalon_st_pipeline_stage.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_avalon_st_pipeline_base.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_traffic_limiter.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_reorder_memory.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_avalon_sc_fifo.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_router_002.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_router.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_slave_agent.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_axi_master_ni.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_slave_translator.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_pll.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_phy_csr.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altdq_dqs2_acv_connect_to_hard_phy_cyclonev.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_mem_if_hard_memory_controller_top_cyclonev.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_mem_if_oct_cyclonev.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_mem_if_dll_cyclonev.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_hps_0_hps_io_border.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_hps_0_fpga_interfaces.sv}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/fpga_debug/debounce.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/fpga_debug/clock_reduce.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/RTL_VB/fsm_spw.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/RTL_VB/rx_spw.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/RTL_VB/tx_spw.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/spw_ulight_nofifo.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_reset_controller.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_reset_synchronizer.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_avalon_st_adapter.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_timec_tx_to_w.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_timec_rx_r.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_pll_tx.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_led_fpga.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_hps_0.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_hps_0_hps_io.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_clock_pair_generator.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_acv_hard_addr_cmd_pads.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_acv_hard_memphy.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_acv_ldc.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_acv_hard_io_pads.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_generic_ddio.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_reset.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_reset_sync.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_iss_probe.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_altdqdqs.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_mem_if_hhp_qseq_synth_top.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_fsm_info.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_data_tx_to_w.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_data_rx_ready_0.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_data_rx_r.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_clock_sel.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_auto_start.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_MONITOR_A.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/rtl_top/spw_ulight_con.v}
add_file -verilog {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/fpga_debug/detector_tokens.v}
add_file -constraint {spw_ulight_nofifo.sdc}
set_option -top_module spw_ulight_con
set_option -technology 
set_option -part 
set_option -package 
set_option -write_verilog 0
set_option -write_vhdl 0
set_option -write_vif 0
set_option -write_apr_constraint 0
project -result_file ./spw_ulight_con.vqm
project -log_file ./spw_ulight_con.srr
set_option -frequency auto
project -run
project -save spw_ulight_nofifo.prj
