* LVDS RD netlist

.SUBCKT LVDS_OCT_LOAD lvdsin lvdsina vccpd vcpad0 vcpad1 vcc
.PROT freelib
5a2Z[7-u#/js;B-i:'%ep$v,C'/25B]+):fJ5H#uC(1y)e-u>9%J;X5i#'%s$B-,(2/e5BvwC'f:9H]uC:xJ5ejH>(%J)[
8
y396L<yz59=xP/9#+Y
\%2<sGTO9-a[.ds!mx:l
+;w6k$;vX#y%k$;vX2s!mx:l
+vw6k$;v=#y%k$;vJ2s!mx:l
+rw6B0ghm#y<Bx:l
+5w6B0Z.4tw6B02p[
8
<?=2'$st9UR.a$X+u3[fe*.:q
%n 2[Mk9FM>2P73x([ +00.pm6
Z
[?#<2:F.'/sW2(91-pB-HM'fi [
gdc9;dJ9g\ /X:$=+hm2*hT33Iy
6
9?80sWaM7U[Gsp:/B:5x3UwS$\L
s23:F.'/sW239127!vPCs%(==vq
y
a&Zt%#*M91-S$j+Cs$\l
svwAuxaW\K=0kx+z$;iM2257<8
/p9;)$/t2<k,'77]X(i s(0.P)6
>!97H3:/XhZ$y+PU257j8
q
5&[(J7%Yob8z$x++P'F:5E*[y
k*23+dk!=x>W%z/.X125!jH):%(==rq
%nH23+DK!=X:$h+peS1ET33Iy
6
9?80sWF\PUH#[W(E1+5<-pe]_0
[E#=6%0781#*0x0Am%3WeEuj5xu)*[J0
[O3+:r- /4\$:/XSZb-h(2257h8
q
5&[(J7\) C=2P!Jjm$*E5.:Q
%[ 280sS'9>d>\%v%9%-($R3w*\h)[
gd3'XzT%/$:/X)ZhuIw(257h8
q
5&[(J7\) C32P!3p)SFt6d8
/3uxZt%/F:FU25!]4(i257H8
/z[/280Ss[912)!YP((257H8
q
5&[(J7\*0x0Am%JW(E1h0jR3m]_0
[=RW+f.'/Sw2(9[(J60WPE )9<3)*[J0
[=5W+f.'/Sw2(9ipV9c :IBE;<up9! YL
s2PW9[>W%z/.X12p73X('*J50.P>6
Z
[?#<2:=;Dj9G\ [x:zX34)'j)6D8
/3sxZdmSk%47H$,9;<w[;$i++M:%Tt33HY
kGH;7\*0X0aM%3w(9 -p=jP9! sl
[
,?+*728,< :/B:P>Jp>/JI [
gU(9[lT## 9xD;$>+lm'1ST33hy
kGJ77\=9=x:$<+,E2v)t334Y
6
9?80sW+Y2z$x++($Hh0>]tT6
>!5b# ;*[2P7Rx):/E)0.pP6
Z
[?#<2:]6/$X+u3/h)0.:q
%'u2680W%MmO3MgW3E*Y($y)*[/0
[bVW2Y32DMsK%47h$>+,32/tT33hy
k%+$.'F:FU2S!-PM/j(==vq
%'J2680WF\PUH#[WmEV:0x])*[V0
[buW2Y328/T2<K,'773x3[Jt;0.pP6
>!5>#t;-X:$E++e$HtT33Iy
6
9?80sW;*[lwS#+H/*:sE5j2jZ
a5e#59=ID[7*5[9f-)B5,M*\H0[
g3(96(8,T/:=6(87yx(IuS00.p)6
>)77')+r.A$ST9ur.A$b+IeSJ(==VQ
%nuj$8< FM>2P7;x>U :*0.p>6
Z
[?#<2:yIPv9')+91-pJ]LE/vi [
g3m96l<YZ59=XAw\k=0KXhZI;I('257<8
/M:x33+dk;*[2dJ#Ph$vy)e<63iz
aAJrw;R- /8< :/x)zB5LE2257H8
q
5&[(J7't'91-5=34c($\L
s;H:y$;$st9UR.a$=+L>'jVt33iY
kUT$8*$:F.'/sW2(9f-9Jv,)*\H9[
g3e96Ig7H3:UB:9h]h9! SL
s;,:y$;$,9;<w[2S!-uMuj(==rq
%:12:.[W+*7Gg7]x>I*E00.pP6
>S77't'9[(J60WcEVt(<;)*[/0
[h-W;]=28/T2<K,'P73x('HS00.pP6
>!)j#525X:$E+U#$%jT33Iy
6
9?80sWF=Dp[S\S!MX:Z$u3e'%I [
gI>9iz.+g/+C8d$ST9ur.A$E+jwUHjT334y
k/+$,\s6k>Z.4twAm7u[gS+:'b:7X3H9! +l
svH:R[g<sG Qw.2dmSk%47H$=+Lp(1Tt334Y
k/T$,\s6k>Z.4twAuxHz>]upi257H8
/>sxL869/%=d7W7\) c32S!;P3:*(==rq
%:F23#/Y%K[GHM# aM7U[Gs+:'B:sbRj9! +L
sr+:R[g<sG Qw.28/t2<k,'77-X3sU:;0.Pp6
>+77% q\>A86cv:]6/$=+3(/FvT33Iy
kvJ$,\s6k>Z.4tw;]=27!-JW$U(==vq
%nV)$,\S6K>z.4TW(9/-(xJ3w*\hs[
8
<?=2'$Nb):/b:)H;LWu$\l
sri:_K($,\s6k>Z.4tw3e/eS=-)*[v0
[<RWJ_22680W3E*t(E;)*[V0
[<5WJ_22Dj#hH:1EsI<63IZ
aA<Uwj_22p7-XEsv+00.P>6
Z
[?#<2:_K!$X++>uUs7<*[Y
kvV$NbD:R[g<sG Qw.27!r3>$/(==rq
%IF2+n2W;]=27!5lPI257<8
/)/xX+o# 9Xd/$<+4((fet334Y
kjH$NbD:FU20!U3Eih(==rq
%nJj$nBd:/XjZ>yjc$257h8
q
5&[(J7B>0YX:Z=-4>$JI [
ghm9kxw8#*m9u-7b3pm*\h)[
gh>9kxw8# aM7U[Gsp:IBt0>;p9! YL
s54:_KD:7*5[9%-9X],E*\H)[
gh)9kxw8#=+C-A[#/#09u-9b5U3*\h0[
ghw9kxw8#>J*X+Z>RpmS257<8
/z2h2+Nt5:/x+zJr3W(257H8
q
5&[(J7% q2JS$x++>Uuh;.:Q
%2F23#/h):Xl869/%=D7w7VxcU/Y)0.pP6
>tP7% q2JS$.'f:[B+*$uj9! +L
sUP:R[g9$vw+F.'/sW239v-*J3J)*\H9[
gjc9iz.$5I:r- /4\$:[B+0=VU9! +L
sU3:R[g9$vwAux)zXvuC'257<8
/z$/23#/H):x:$J+uM'1Tt33iY
6
9?80sWF=DY*x#+H//j;$]U2jZ
a(<#=+cjVp7% Q\>a86CV::b)*H;u9! +l
sUH:R[g9>jw;]=27!U4(u*(==rq
%$*23#/he/XzDMsK%47:$<+j)2 )T33hy
k*V$,\s)s123+dk!=xHz<U3p2257<8
/W(xL865L(9;)$=+,Mshet334Y
kGVp7% Q2h:$X#3h'*s0<<63:z
0
N|\) 9iz.>J3:/B:P>JjP$%I [
gl39iz.>J3:]6/$>+I)I*)T33hy
khJ$,\sE/U288< :'bs;X]P9! yl
sY3:R[g*X;wf\puh#[wMeUT0HU)*[j0
[>VWF=DvPj#*m9*-0$5h#*\h9[
gdeIXl86y+m9120!;3>(J(==RQ
y
a&Zt%#=+ch:)7jX(/*+pHrTt6
>v97% qS1S$8*$:(B))hRl9! YL
sYJ:R[g*Xvw+*7gG7-Xpi V;0.P)6
>v*7% qS1S$,9;<W[2s!V4)UH(==5Q
%SF23#/l(:X>s73xc( Y(0.pP6
>!;x#=+CH:)7JW>E1E;>3)*[V0
L
F& 9XxL86]P(91-pXjHW/*JS.:q
%nFh$,\S#[12P75xw/*js0.p)6
Z
[?#<2:R[g;=3w(e1:pJ-3C[fi [
g,c9iz.E3p:r[G*x;W3E t(I5)*[*0
[O]3:r[G;=3W(9u-7=VIc*\h9[
8
<?=2'$,\s#[/2p!j+(u%:S<rTt6
>!;h#=+CFh)7JWmE%:s<R)*[J0
L
F& 9XxL86]Pp91-pXjH#ifHS.:q
%(V23#/,3IX3T#%v%9V-9>5+e*\h9[
gd#2Xl86]pP9127!-jm/J(==5Q
y
a&Zt%#=+cfH;7jX(/1y9iv4)]_0
[O]j:r[G;=]W(9J-9IV4)*\h9[
8
<?=2'$,\s#'12p!j+(uU:;$*[Y
kGe*7% Q(%:$X#3hu1e90.P)6
Z
[?#<2:R[g;B3w(e1:pijH)/vi [
g,#9iz.E-p:=2'.1#4H$J+Pb<632Z
aA=j+:R[g;B3w(9 -SX3+M*\H9[
8
<?=2'$,\s#'%2p!j+(uU))e5Tt6
>!7x3WF=DE5b#+:UB)sh]h9! YL
[
,?+*723#/,cUX:ZxJ3>$F+).:Q
%[1j$,\S#'u2[Mk9FM>25!RhPSu(==RQ
%n :s7% q(%)$x#,H[ut7b<632Z
0
N|\) 9iz.E-I:/B:Pj;h>SJI [
gp(:Xl86]U>9>d>\%v%9%-)E-Im*\h0[
gd3/V23#/,c:X:$>+jc:ujT33hy
6
9?80sWF=DEsb#+H/1h*=V,w]_0
[O3+)9iz.E;U:/XhZ>3I#$257<8
q
5&[(J7% q(u+$x++([H:P>RtT6
>!7xuWF=DEs<#+:[BvPxy49! +L
[
,?+*723#/,mSX:Zx3+c2V)6d8
/3/h23#/,MsxL869/%=d7W7vXC/Us(0.Pp6
>!7x]WF=DEs>#+:2B:9=yI9! +L
[
,?+*723#/,m(X:ZxJ,)Su)s.:Q
%[ :$,\S#UF23#/Y%K[GHM#4H[u+sb<63IZ
aA=3P:R[g;J]w(9/-0HY+3*\H0[
8
<?=2'$,\s#:12p!j+#'heS>*[Y
k H57% Q(/:$,\s6k>Z.4twpe H7<-)*[v0
[O3pm9iz.EV+:/XSZ=uje2257<8
q
5&[(J7% q(/h$x++((*S;I3tT6
>h7h#=+CFS77% q\>A86cv:IBv5Iy49! +L
s2P3ixL86]i3912S!]u3sj(==rq
y
a&Zt%#=+cfs57jX(/fT*JYu2Jz
a7=5wf=de)B#=+c-a[#/#09v-)<]i3*\H0[
gd3[*23#/,>'X:$h+3c:/hT334y
6
9?80sWF=DE)j#+H/ hP=3tT6
>h7>#=+CFSs7% q\>A86cv::Bt*IJU9! +L
s2P3(xL86]iM9129!-u>/%(==rq
y
a&Zt%#=+cfs)7jX([ :;HrTt6
>h5x#=+CFS)7% q\>A86cv::Bt7x5,9! +L
s2PC[xL86]i>9129!;LMs%(==rq
y
a&Zt%#=+cfs07jX(/fTp=UH2Jz
a7B-wf=de)<#=+c-a[#/#09v-Se33M*\H0[
gd3'u23#/,>IX:$h+33//)T334y
6
9?80sWF=DE)$#+H/1E*=ul3]_0
[=-I:r[G;h5WF=Dp[S\S!MX+Zh3,#2257<8
/z[%+$,\s#:j2p7vXM(*V00.Pp6
Z
[?#<2:R[g;HUw(e1H7=33)]_0
[=-h:r[G;huWF=Dp[S\S!MXSZ>5+w2257<8
/z[%T$,\s#:*2p75XCi%VS0.Pp6
Z
[?#<2:R[g;HYw(e1:;i5L>$$\l
s3uE9IZ.evL:R[g<sG Qw.20!vL#u257<8
/z[%e$,\s#:h2p7vXC$fH*0.Pp6
Z
[?#<2:R[g;H]w(e1:;>YL#]_0
[=;+:r[G;h]WF=Dp[S\S!MX+ZI]h([257<8
/z[UH$,\s#:f2p7vX((%V;0.Pp6
Z
[?#<2:R[g;<jw(e1:;JYiC2$\l
s33C9IZ.er+:R[g<sG Qw.20!-i>s257<8
/z[U)$,\s#i12p7vX3ufs90.Pp6
Z
[?#<2:R[g;<3w(e1:;$-P>'$\l
s33>9IZ.erP:R[g<sG Qw.2)!],3(U(==rq
%n )07% q(Vh$x#IH2%E)><63IZ
0
N|\) 9iz.ERU:/B:7xVh(U$\L
s33)9IZ.eru:R[g<sG Qw.2)!3JM//(==rq
%n )(7% q(Vj$x#hH'Ht5<<63IZ
0
N|\) 9iz.ER3:/B:PE5l>:uI [
gpmSXl86]4m9iz.+g/+C8d$<+l>$u+T334y
kGHSe#=+cf+S7jwMeh)(XY)*[v0
L
F& 9XxL86]4>91-pX]JCi H6D8
/3:123#/,p:xL869/%=d7W7rX>u/+(0.Pp6
>!7h3WF=DE0h#+::Bj;xRI9! +L
[
,?+*723#/,PIX:Zx3+#S%t6d8
/3:%23#/,pixL869/%=d7W7vXW$*V70.Pp6
>!7h;WF=DE0<#+:2BjPhy,9! +L
[
,?+*723#/,P2X:ZxJ,(/1E9.:Q
%[/S$,\S#IJ23#/Y%K[GHM#IH(uSs<<63IZ
aA=v4:R[g;<5w(9/-p$5H3*\H0[
8
<?=2'$,\s#i*2p!j+#:/V0<*[Y
k s97% Q(vT$,\s6k>Z.4twpe1Vp=;)*[v0
[O3Iw9iz.ERj:/XSZj5l>'257<8
q
5&[(J7% q(Vv$x++3/%j0I*[y
k s*7% Q(vV$,\s6k>Z.4tw>e%J;ev)*[v0
[O3I#9iz.ERl:/X+ZE]4w(257<8
q
5&[(J7% q(VE$x++3/ :7h*[y
k +p7% Q(ve$,\s6k>Z.4tw>eU)5=Y)*[v0
[O3439iz.ER,:/X+ZI5,cI257<8
q
5&[(J7% q(J:$x++((/j7I;tT6
>h0b#=+CFYP7% q\>A86cv:IB:)xVI9! +L
s2PpuxL86]H(912)!;L3'f(==rq
y
a&Zt%#=+cfy77jX(/heS<j42Jz
a7<vwf=de9=#=+c-a[#/#09v-7JYPC*\H0[
gd3IV23#/,)[X:$j+j#2F)T334y
6
9?80sW7Y3W80sS;b>:$x++(Uu+sxVtT6
>h0$#O;-LzT%/5<K12680WmE vT33hy
k +(745[q[(j6'k%/xL<yz#+5xyzH3+):257$8
/z[vV$)'F==2'.8z/(9125!;,M(h(==rq
y
a&Zt%#o;-lZt%/5<k 2p!j+MifV7.:q
%[VE$)'f==2'.8Z/39iz.>J3:IB);=JU9! YL
s3H(9E3x5\) c6u[=#>jm627!54#[U(==5q
%[Jh$)'f==2'.8Z/396(8,T/:UBS7IVI9! YL
s3HC9E3x5\) c6u[=#=6%0781#Hhu*H90.P)6
>h9j#O;-LzT%/5<K 2Dj#3HIF:P$<632Z
aA=5i:36/-#<2Qy0a77jw3ev+0=Y)*[v0
L
F& 9XxF:-E 9Xd3/s-w(e1:S$3,)($\l
s3Hp9E3x5\) c6u[B#T;-xHzJ]H>u257$8
/32j2'80'+*7g:9Gu:R- /4\$:ibT0=539! yl
s2P)$xF:-E 9Xd3/s-w(9%-;XvLE*\H0[
8
<?=2'$)'F==2'.8z/M91-pXvLWifT6D8
/32h2'80'+*7g:9G3:R- /4\$:[b:p>YP9! +l
s2P)(xF:-E 9Xd3/s;w(9U-*$UPW*\H0[
8
<?=2'$)'F==2'.8zV(91-pX;P)$%T6D8
/3$12'80'+*7g:9t+:R- /4\$::by;J339! yl
s2PW[xF:-E 9Xd3/mjw(9%-9eU,)*\H0[
8
<?=2'$)'F==2'.8zV391-pX;3Cs*y6D8
/3$%2'80'+*7g:9tP:R[g<sG Qw.20!r+M$*(==5q
%[*)$)'f==2'.8Zv39[>w%Z/.x 2s!5U#S%(==5Q
%[*S$)'f==2'.8Zv39;dJ9g\ [XYZbVI>I257$8
/z[*+$)'F==2'.8zV39127!U,((j(==rq
y
a&Zt%#o;5lZt%/5<k12p!j+Mu%sp>*[Y
k T9745'q[(j6'k%/x361#3h:fTp=<632z
a7iUw7y=w80Ss;B>:$,9;<w[20!],>(/(==5q
%n t*745'Q[(J6'K%/X:$b+3w:HvT334y
6
9?80sW7Y=W80sS;b>h$x++(Uuj9x;tT6
>h(E#O;5LzT%/5<K 23#/l(:X+ZIujc(257$8
/3s12'8['+*7g:9GP:=2'.1#Ph2*e*H<632z
a7>3w7y=w80Ss;B>H$,9;<w[20!UH):h(==5q
%n v5745'Q[(J6'K%[X:$b++(UJtT334y
6
9?80sW7Y=W80sS;b>j$x++(UV+(<RtT6
>h*j#O;5LzT%/5<K%2:.[W3Euv(>V)*[J0
[=yI:36;-#<2qY0A57%Yob8z$<+j3$*tT33hy
kGH*<#o;5lZt%/5<k%2p7-XE:je;0.Pp6
Z
[?#<2:36;-#<2Qy0aS7jX(//V(<-J2Jz
a7>5w7y=w80Ss;B>)$,9;<w[27!jip2%(==rq
%n v(745'Q[(J6'K%UX:$j+lc(J+T334y
6
9?80sW7Y=W80sS;b.:$x++(Uuh*xRtT6
>h*>#O;5LzT%/5<M123+DK!=XSZ=]lw2257$8
/z[he$)'$==2'.8zV(9125!Y,E[h(==rq
y
a&Zt%#o;5lZt%/5<m 2p!j+M'fJ5<*[Y
k ep745'q[(j6'k0[xL869/%=d7W7rX3(hH70.P)6
>h;=#O;5LzT%/5<M 28/T2<K,'P7;xm/ ET33hy
k e5745'q[(j6'k0[x>W%z/.X120!5PE/h(==5q
%n Es745'Q[(J6'K0[X:$=+le//ST334y
6
9?80sW7:Ll865Uw91-Pxupw/uh6d8
/3(/2'HE=+cjJ(7b>0yx+zBUHCu257$8
/3(v2'HE=+cjJ(7*5[9v-)$YLC*\H0[
gd3(J2'he=+CJj(7JW3E ts>u)*[V0
L
F& 9XxF)5% Q2%V$X++($%+*>vTt6
>h;I#O>Qiz.$-l:_kd:75xw'/t*0.p)6
>h;>#O>Qiz.$-l:]6/$<+IwU/tT334y
kGH;e#o>qIZ.$-L:/xHz=3uE(257<8
q
5&[(J743=r[G9buW(E1:(h34)]_0
[bJ+:3uW3#/hc$X361#4HI1j;<<63IZ
a5X3w7ulL865uW9[(j60w>efy7B;)*[j0
[O-+c9e)-,\S)'*2P73x>[J+s0.pP6
Z
[?#<2:3Uw3#/HCsx:zXjH#'hs7.:q
%'1)$);'F=DY5>#525X+Zh-4wI257<8
/C//2'JE=+cjJ*7\) c329!j+E/%(==5q
%n%:0743=r[G9byW(9F-P=yhP*\h9[
8
<?=2'$)5i)/3wdX#+h/1+pJ;u2Jz
a5X5w72/yp-E*(96L<yz59=xTze53($257$8
/z'1T$)5i)/3wdX#+:'be5iY,9! +l
[
,?+*72'$Vh(-L>77Jx(/%+sx-I2jZ
a5XYw72/yp-E*39Ey)$jF=F120!54)(j(==5q
%'1E$)5I)/3WD=#t;-XhZ<-4mI257$8
/C[12'$vH(-l>77hV B>]j=#uhi%V0=<632z
aAB3P:3js9X0'A[x:$=+uMiv(==rq
y
a&Zt%#o):j:x5hu:/b:pHr3E'ji [
gU3'Xf9h5+[Q;j$/T2<K,'77;xwI/v)0.p)6
>j7j#O):J:X5HU:=6(87;x($u:90.p)6
>j7h#O):J:X5HU:]6/$=+h>IF(==5Q
%' +$)5I)/3WDb#5F\PU:0\WmE%:7I])*[J0
[O-p)9eY)$Jf=f%2P7-xm'uv*0.pP6
Z
[?#<2:3js9X0'+'x:zXj4>'fs*.:q
%' t$)5I)/3W8b#*0x0Am%3W3E*YP=V)*[J0
[b3l:3JS9x0'+'Xz:0\WPEJY(h;)*[J0
[b3,:3JS9x0'+'XI:-#pH$1)5$<632Z
a5Bjw72/yp-E C9Ey)$jF=F%2S!rPW(%(==5q
%n%j774h>21/-#-W(9u-(h-U9! +L
[
,?+*72'$Vh(-L'J=#+H/1h)=5pP]_0
[b-U:3JS9x0' x 2'$Vh(-Lz573x3[*+00.p)6
>j5j#O):J:X5s239eY)$Jf=f%2;!ypm'V(==uQ
%'%S$)5I)/3WJ%3W;r- /8< ::B)9<R39! YL
s-up9Ey)$jF=X7H$#')+9/-5<jL)*\H([
gdc'J2'$Vh(-L'J=#+:IBS*<yU9! YL
[
,?+*72'$Vh(-L'Jb#+H/1h7hV+m]_0
[b-j:3JS9x0' x%2'$Vh(-L>P7Vx('/:s0.p)6
>j5>#O):J:X5s2c9iz.+g/+C8d$$+IcI/ET33jy
kGJ5e#o):j:x5S2C9120!-J(2%(==5q
y
a&Zt%#o):j:x5b>'91-pXjL(ih+7.:q
%'u:$)5I)/3W+n[W72/YP-e c9/-0<uU>*\h([
gUm[Xf9h5+[Qkxg74h>21/-/-WwEFtP$;)*[*0
[b;U:3JS9x0'J_=2'$Vh(-L>P7Rx>/1S00.pw6
>!5j;W72/YP-e>J5X:$b+3w:/vT33hy
6
9?80sW72/YP-e>J-X:ZxJ+wS*)9E*[y
k%))74H>21/-NbF:3js9X0'A'xHzH3u>i257$8
/Cuv2'$vH(-lX+-#o):j:x5hP:$b:*JU)*[*0
[b;h:3JS9x0'J_32:,9;<Y2z$I+h#'*tT33jy
kGJSi#o):j:x5b>[9127!54C2f(==5q
y
a&Zt%#o):j:x543=3Mi-#jw(e1:p=vJEu i [
gUmSXf9h5+[Qe)-)kt==12'$Vh(-Lz57Vx>:1E90.pe6
>jsE#O):J:X543=3mI-#JW72/YP-e*c9J-0b;j)*\h([
gU>/Xf9h5+[Qe)-)kt==12DMsK%47h$<+U#I hT33jy
kGJ)=#o):j:x543=3Mi-#jw(9%-0BjPM*\H([
8
<?=2'$)5i)/3w3#/4(ux:zXj+Cu1Hpe*[Y
k%s574H>21/-,\sp/U2'$vH(-lZ573X)2UV90.PW6
>!5h;W72/YP-e=+CV:s7JWcE ))I3)*[J0
L
F& 9XxF9H5+[qIZ.<ji:/b:pX-L>i*s6D8
/C:/2'$vH(-lL86r+>9Ey)$jF==%27!jP)if(==Uq
%'/+$)5I)/3W3#/4(:Xf9h5+[Q;j$E+l>$HtT33ly
kGJ)$#o):j:x5% Qi1s$X#uh2/+90.P)6
Z
[?#<2:3js9X0'f=d+pi#+h/1:7<YP#'$\l
s2u>$xF9H5+[qIZ.<jJ:/xHzX33W:257$8
q
5&[(J74h>21/-,\SP/H2P!J+(U/h*IutT6
>j)>#O):J:X5% qI1v$)5I)/3W3#/4($X+Z$ype(257I8
/C:f2'$vH(-lL86r+E9Ey)$jF=F127!r4C[v(==Uq
%n%+P74h>21/-,\SP/H2P7-x)(V)90.p)6
Z
[?#<2:3js9X0'f=d+pe#+h/1:7<v4(($\l
s-439Ey)$jF=R[g0X]w72/yp-E*(9j-SH-3W*\H*[
gdcI%2'$Vh(-Ll86R+#912;!JhP:u(==uQ
y
a&Zt%#o):j:x5% Qi :$X++(/ +9evL2Jz
a5<;w72/yp-E=+cvHp7hV B>]j=#4h'he)0.PE6
>!5<VW72/YP-e=+CVhP7JW3EVh9<y)*[J0
L
F& 9XxF9H5+[qIZ.<3P:/b:pX;ip2 )6D8
/Civ2'$vH(-lL86rP39Ey)$jF=R[g0X]wpe*+7Bv)*[*0
[bRh:3JS9x0'F=D+7=#O):J:X5H+:[B+0IVp9! tL
s2up$xF9H5+[qIZ.<3P:/xJzi-4C2257$8
q
5&[(J74h>21/-,\SP[%2P!J+([Jt0=]tT6
>j0>#O):J:X5% qI j$8%Yob6(873x('uj70.pw6
>!5<]W72/YP-e=+CVh57JW3E1:5jy)*[J0
L
F& 9XxF9H5+[qIZ.<3J:/b:pX;,M[ T6D8
/C212'$vH(-lL86rPW9Ey)$jF=R[g0=-wpe*:)>Y)*[*0
[b5p:3JS9x0'F=D+7I#5F\PU:0\W3EFt7Iu)*[*0
[O-hc9eY)$Jf=r[G0=uW(9u-7$;49! YL
[
,?+*72'$Vh(-Ll86Rpe91-PxJ3m(1h0.:Q
%'J)$)5I)/3W3#/43SX33+DK;*[27!u,3/u(==uQ
%n%Y)74h>21/-,\SP[H2P7-x)'1hT33hy
6
9?80sW72/YP-e=+CVh;7Jx(/1h0>Jh)]_0
[b54:3JS9x0'F=D+7E#O):J:X5% qI v$<+,((/(==uQ
%n%Y974h>21/-,\SP[F2P7]xe(*jT33jy
6
9?80sW72/YP-e=+CVj57Jx(/1h)=-4)]_0
[b5j:3JS9x0'F=D+5b#O):J:X5H+:(BjPIyp9! tL
s-HE9Ey)$jF=R[g0B-w;R- /8< :$by5H5,9! Vl
s2u)(xF9H5+[qIZ.<-u:/xHz=]iC[257i8
q
5&[(J74h>21/-,\SP'u2;!V4([/(=xRtT6
>j(x#O):J:X5% qI%)$)5I)/3W3#/4c'XjZE5p((257I8
/C$ 2'$vH(-lL86ruM9Ey)$jF=F125!3LW/f(==Uq
%n%t574h>21/-,\SP'u2P7;xe:VS)0.pw6
Z
[?#<2:3js9X0'f=d+5H#,h[h+(=<6(i$\l
s2uWuxF9H5+[qIZ.<-i:/xyzirL>u257i8
q
5&[(J74h>21/-,\SP'V2P!J+([u)5xVtT6
>j(h#O):J:X5% qI%+$)5I)/3W3#/4c:XjZh-jcS257I8
/C$v2'$vH(-lL86rup96L<yz59=xHzB-,>*\H([
gdc$J2'$Vh(-Ll86RUP912;!5hm$/(==uQ
y
a&Zt%#o):j:x5% Qi%T$X++(/Uy7HUi2Jz
a5iUw72/yp-E=+cvJ(74H>21/-,\sp'U2)!rHp[U(==Yq
%'*v$)5I)/3W3#/4c$Xf9h5+[Q7'573xP/uh70.p)6
>j(E#O):J:X5% qI%t$)5I)/3WDx#jH:1:*j<63$Z
aABY+:3js9X0'f=d+5i#+:[b)5<Y,9! yl
[
,?+*72'$Vh(-Ll86RU#9F-7xuhP*\:0.:Q
%'Hh$)5I)/3W3#/4c(X33+DK;*[25!yj>'/(==yQ
%n%v574h>21/-,\SP'F2P75x>[Jh(0.pw6
Z
[?#<2:3js9X0'f=d+SX#+h/1:7B;J>]_0
[by3:3JS9x0'F=D+sx#O):J:X5% qI%E$b+I(:1YT33jy
k%V)74H>21/-,\spu12:,9;<y2Z$=+3M[*+t33JY
kGJ*<#o):j:x5% QiU:$X#Lh2UV5J<63$z
0
N|\) 9eY)$Jf=r[G0j3WeE1t0>R)*/VI [
gdcSJ2'$Vh(-Ll86R339120!5lmUJ(==uQ
y
a&Zt%#o):j:x5% QiUJ$X++(/ s7$]H2Jz
a5>Uw72/yp-E=+cv)574H>21/-,\spu 25!;,C:f(==Uq
%'Hv$)5I)/3W3#/4m'X33+DK;*[2;!R4#$V(==yQ
%n%v;74h>21/-,\SPU%2P73x(S%h70.p)6
Z
[?#<2:3js9X0'f=d+S<#+h/1:SX-,Es$\l
s-,(9Ey)$jF=R[g0Jrw72/yp-E*39 -0B3PE*\H9[
gU#[Xf9h5+[Qiz.<;4:3JS9x0'a/XjZ=;,e'257I8
/C(%2'$vH(-lL86r3p9;Dj9G\ [xJzHr33'257i8
/z'f)$)5i)/3w3#/4Mix:$e+3Ei*st33JY
6
9?80sW72/YP-e=+CV)97Jx(/1j*>y,P]_0
[b]I:3JS9x0'F=D+s$#O):J:X5% qIu+$=+p(S%tT33jy
k%e074H>21/-,\spuj2'$vH(-l'j=#Ph[vy*><63$z
a5e5w72/yp-E=+cv)974H>21/-/-w3e/Tp>5)*[j0
[b]j:3JS9x0'F=D+s$#5F\PU:0\WmEVE)=V)*[*0
[O-,e9eY)$Jf=r[G0j5W(9H-sb34w*\h([
8
<?=2'$)5i)/3w3#/4M$x:zXj+C$h+0>*[Y
k%e;74H>21/-,\spu*2'$vH(-l'j=#Ph2*:)i<632z
aSXjw72/yp-E=+cv)(7'=6%03t##PhsvH;H<63$z
aAJjP:3js9X0'f=d+Si#+:(bJ;e3u9! Tl
[
,?+*72'$Vh(-Ll86R3#91-PxJpP:Jh).:Q
%U1j$)5I)/3W3#/4m(Xf9h5+[Q;j$>+4e:257I8
/M/U2'$vH(-lL86r3#96L<yz59=xyz$Uupi257>8
/zu1s$)5i)/3w3#/4M(x:$$+u3/ yt33JY
6
9?80sW72/YP-e=+CVSP7Jx(/1)7b]U>]_0
[jJ4:3JS9x0'F=D+)x#O):J:X5\U:[B:(xJl9! tL
s;+)9Ey)$jF=R[g0Hjw+y2Z$=+,#(j(==5q
%nu:(74h>21/-,\SP:12P73x('%Y)0.p)6
Z
[?#<2:3js9X0'f=d+)J#+h/1:0=3+(s$\l
s;+E9Ey)$jF=R[g0H;w72/yp-E>j5x)z>]PC*\H9[
g3((Xf9h5+[Qiz.<V3:3JS9x0'a'XjZjy+>[257I8
/M[12'$vH(-lL86riM9Ey)$jF=F12S!vP32/(==Uq
%nuh774h>21/-,\SP:u2P75xm(Jv70.pw6
Z
[?#<2:3js9X0'f=d+)H#+h/1:)>Y3E$$\l
s;PC9Ey)$jF=R[g0Hvw72/yp-E>j-x)zJ;+#*\H9[
g33UXf9h5+[Qiz.<VI:3JS9x0'a'XSZh3UPU257I8
/M[/2'$vH(-lL86ri>96L<yz59=xJzH53C*\H([
gdm[V2'$Vh(-Ll86RI>912*!54m( (==uQ
y
a&Zt%#o):j:x5% Qi/+$X++(/ T;>ju2Jz
aS=5w72/yp-E=+cvs074H>21/-/3w3e1:(X5)*[j0
[j3j:3JS9x0'F=D+)<#O):J:X5H+:IBE;<JI9! vL
s233sxF9H5+[qIZ.<v4:/xTzJ3+3:257i8
q
5&[(J74h>21/-,\SP:J2P!J+(UF:)hutT6
>)7E#O):J:X5% qI/Y$)5I)/3W8b#UH'uhs0.p)6
>!sbJW72/YP-e=+CVS97JW3EJts=y)*[J0
L
F& 9XxF9H5+'q;:$X++(i1:SJ]Tt6
>)5=#O):J:g5H+:YipV9')+9H-s<J3c*\h9[
g3c'Xf9h5+'Q;:$8*$:[Bt7E])*[J0
[O;Um9eY)$J$=f12P7-x)I*))0.pP6
Z
[?#<2:3js9X['A[x:zXjupsUV7.:q
%U%S$)5I)/=WD=#O):J:g5H+:IB+;juh9! YL
s;up9Ey)$j$=F 2:.[w3e%ypJ<632z
aSB5w72/yp1E*39;Dj9G\ /xJzJY+W2257$8
/zu%T$)5i)/=wd=#+:[b)S>U49! +l
[
,?+*72'$Vh(5L>57Jx(//Y5<V42jZ
aSBYw72/yp1E*C9;Dj9G\ /x)zH5i)$257$8
/M'f2'$vH(5l>57\=9=xJze5+M'257$8
/Mu12'$vH(5l>57'=6%03t##3h'j)90.P)6
>)s=#O):J:g5HU:Y$;$=+he$ jT33hy
kG)SB#o):j:G5hu:/xJzJ;JEi257<8
q
5&[(J74h>21;-#-W(E1:0hJ+m[$\L
s;3M9Ey)$j$==%2'$vH(5l>57rX(ihV(0.P)6
>)sh#O):J:g5\U:=i(87Rxw/J:s0.p)6
>!sjRW72/YP1e c912s!y,)(%(==RQ
y
a&Zt%#o):j:G5S2391-pX3iC[1T6D8
/Muj2'$vH(5l'j=#o):j:G5\u:[b)*>UP9! yl
s;3W9Ey)$j$=X7H$)5i)/=wdB#Jh(j:;e<63$z
aSJYw72/yp1E2 [x33+dk;*[2)!vL)//(==5q
%UuE$)5I)/=WJ%3W+r2z$I+3eU%vT33jy
kG))X#o):j:G5S239120!3Jp:/(==5q
y
a&Zt%#o):j:G5S2C91-pX3Pp$1V6D8
/M: 2'$vH(5l'jB#o):j:G5h+::b:7H-H9! yl
s;iC9Ey)$j$=X7J$,\s6k>Z.4twWe*s7H;)*[*0
[O;Im9eY)$J$=x7j$x#4H[*Y)<<632Z
0
N|\) 9eY)$J$=_k;$x++(/Hh0I;l2jZ
aSHvw72/yp1E>j5xF9H5+'q[J$H+J3uvVt33JY
kUs074H>21;-Nb$:3js9X['A'xHz=3i)i257$8
/M:j2'$vH(5lX+1#o):j:G5h+:[bH*$3)*[j0
[O;Iw9eY)$J$=_k;$x#UH[%SP<<632Z
0
N|\) 9eY)$J$=_k/$x++(/HS7x5tT6
>))>#O):J:g5B>[9eY)$J$=f%27!RUw$u(==5Q
%U/E$)5I)/=W+n0W72/YP1e*39*-7bJU9! tL
s;4(9Ey)$j$=_K/$8%yOB6(87]X((fs00.PW6
>!s<3W72/YP1e>J-X:$=+j(2JvT33hy
6
9?80sW72/YP1eOmQeO65\+:/B:Px3pm'uY6d8
/Mi%2'$vH(5lFS5492q[:$)5i)/=w8B#ih/%s(J<63sz
aS<;w72/yp1EoMqEo65\+:3js9X['A'x)z<j4Es257i8
/Mi/2'$vH(5lFS5492q[:$/t2<k,'p7rX>' H00.PW6
>!s<RW72/YP1eOmQeO65\+:/XhZE]I((257I8
q
5&[(J74h>21;-,\SP/u2P!J+('u)P=ytT6
>)0$#O):J:g5% qI1)$)5I)/=W8b#pH:V+7$<63$Z
aAJrJ:3js9X['f=d+pJ#+:'bH*H5H9! yl
[
,?+*72'$Vh(5Ll86R+>91-PxJ3([ +*.:Q
%nu+*74h>21;-,\SP//2P7;x([ +*0.p)6
Z
[?#<2:3js9X['f=d+pi#+h/1:7<]JE]_0
[O;4#9eY)$J$=r[G0xuW(9F-;=]p9! tL
[
,?+*72'$Vh(5Ll86R+e91-PxJ3m$Hv5.:Q
%UJ:$)5I)/=W3#/4(SXf9h5+'Qiz.<Jj:2B:0>]U9! tL
s;H39Ey)$j$=R[g0XYw72/yp1E*(9 -5>33C*\H([
gdm2%2'$Vh(5Ll86R+e9125!5I>$F(==5Q
y
a&Zt%#o):j:G5% Qi1e$X++(/ y)>Yu2Jz
aS$;w72/yp1E=+cv:;74H>21;-/jwWefe*=v)*[h0
[O;h>9eY)$J$=r[G0x]W(9F-*bJ3>*\h([
8
<?=2'$)5i)/=w3#/43/x:zXj+3uv:(<*[Y
kUy074H>21;-,\sp[12dmSk%47:$H+L)u*yt33LY
kG)9$#o):j:G5% Qi :$X#Phu1J7=<632z
0
N|\) 9eY)$J$=r[G0=3W(E1:PjJUP//I [
g3)$Xf9h5+'Qiz.<3p:3JS9x['F=D+PE#4HSJvP<<63$Z
aS$Yw72/yp1E=+cvH774H>21;-/jwCeU:p>])*[*0
[O;h#9eY)$J$=r[G0=3W(9%-5xyp>*\h9[
8
<?=2'$)5i)/=w3#/43'x:zXj+3iUH5=*[Y
kUTp74H>21;-,\sp[%2:,9;<y2Z$$+HW$jTt33LY
kG)(=#o):j:G5% Qi J$X#Lh( y;e<63$z
0
N|\) 9eY)$J$=r[G0=uW(E1:PjRpw$$\L
s;JC9Ey)$j$=R[g0=Uw72/yp1E=+cvH57rXW'*)S0.PW6
>)(j#O):J:g5% qI t$8%Yob6(87-xPUHv70.pw6
>!sIVW72/YP1e=+CVh(7JWcEJE7x])*[J0
L
F& 9XxF9H5+'qIZ.<3L:/b:pX;ip(%+6D8
/M$v2'$vH(5lL86rPE96L<yz59=xJzX]P3i257i8
/zu*y$)5i)/=w3#/43sx:$B+Hp'*Jt33HY
6
9?80sW72/YP1e=+CVh;7Jx(/1jP>53m]_0
[juj:3JS9x['F=D+7E#O):J:g5% qI v$<+,w: ST33jy
kG)(>#o):j:G5% Qi e$X#Ph:hV;=<632z
0
N|\) 9eY)$J$=r[G0b-W(E1:P=;,([JI [
g3w(Xf9h5+'Qiz.<-U:3JS9x['a/XvZI5+3:257I8
/Ms12'$vH(5lL86ruC96L<yz59=xHz=jH):257i8
/zuhH$)5i)/=w3#/4C'x:$=++)i1Vt33JY
6
9?80sW72/YP1e=+CVjs7yx#[ ts0.+P]_0
[jyU:3JS9x['F=D+5j#O):J:g5% qI%j$b+,)(*(==uQ
%UH)$)5I)/=W3#/4cUXf9h5+'Q;:$b+4eI1tT33jy
kG)*H#o):j:G5% Qi%)$X#3h/ :5J<63$z
0
N|\) 9eY)$J$=r[G0bVWeEu)(>5)*/VI [
gdmSV2'$Vh(5Ll86RU>9120!up3U/(==uQ
y
a&Zt%#o):j:G5% Qi%+$X++(/ TS>5,2Jz
aS>5w72/yp1E=+cvJ074H>21;-,\sp'/25!5u)iU(==Uq
%UHt$)5I)/=W3#/4cIX33+DK;*[27!;j32H(==uQ
%nuv*74h>21;-,\SP'V2P73xmUHv(0.p)6
Z
[?#<2:3js9X['f=d+5i#+h/1:SX-J3s$\l
s;L#9Ey)$j$=R[g0BUw72/yp1E=+cvJS7;X>2*J50.PE6
>);x#O):J:g5% qI%t$)5I)/=WJ%-W3EJ:0E;)*[J0
[j]p:3JS9x['F=D+5I#O):J:g5H+::B)9>RU9! tL
s23#'xF9H5+'qIZ.<-J:/xezH]JCu257i8
q
5&[(J74h>21;-,\SP'F2(!uIcU*(=xRtT6
>!sE;W72/YP1e=+CVj;7JWPEu+0$R)*[*0
L
F& 9XxF9H5+'qIZ.<;+:/b:pX33C[hJ6D8
/M(/2'$vH(5lL86r3(9Ey)$j$=R[g0B]wCeUV9i;)*[*0
[j]4:3JS9x['F=D+sx#5F\PU:0\W3E :5xu)*[*0
[O;,)9eY)$J$=r[G0jJW(9F-(b]IP*\h([
8
<?=2'$)5i)/=w3#/4M[xezX5,W[25p<*[Y
kUe(74H>21;-,\spu 280Ss'9%-;ir+#*\H*[
gdm(H2'$Vh(5Ll86R339129!;Ic/*(==uQ
y
a&Zt%#o):j:G5% QiUJ$X++(/ )7<]u2Jz
aSe]w72/yp1E=+cv)574H>21;-,\spu 25!v3([U(==Uq
%:1:$)5I)/=W3#/4m'X33+DK;*[2(!V3cIJ(==yQ
%n/:774h>21;-,\SPU%2P7]x#SVv00.pw6
Z
[?#<2:3js9X['f=d+S<#+h/1:5>]4Wi$\l
sv+C9Ey)$j$=R[g0Jrw72/yp1E*39 -0=3,3*\H9[
gI(UXf9h5+'Qiz.<;4:3JS9x['a/XjZ=J,#:257I8
/>//2'$vH(5lL86r3p9;Dj9G\ /xJzX-332257i8
/z:1+$)5i)/=w3#/4Mix:$>+H321Vt33JY
6
9?80sW72/YP1e=+CV)97Jx(/1)7<yh2jZ
a)X5w72/yp1E=+cv)974H>21;-,\spuv27!jL#' (==Uq
%:1t$)5I)/=W3#/4m2Xf9h5+'Q7'773x3UF+00.pw6
>SP>#O):J:g5% qIuY$)5I)/=WDb#pHI E($<632Z
a)X]w72/yp1E=+cv)97'=6%03t##ihuUT5i<63$z
aAH3+:3js9X['f=d+S$#+:(bV5B;J9! Tl
[
,?+*72'$Vh(5Ll86R3w91-PxJU>Iu:7.:Q
%: h$)5I)/=W3#/4m$Xf9h5+'Q7'773xP[%hT33hy
k/H574H>21;-,\spu*2:,9;<y2Z$=+,W2vHt33JY
kGs7J#o):j:G5% QiUT$X#Jh:UJ9$<63$z
0
N|\) 9eY)$J$=r[G0j]W(E1:P=5hc'*I [
gI3:Xf9h5+'Qiz.<;,:3JS9x['a'XEZjJ+>:257I8
/>[v2'$vH(5lL86r3#96L<yz59=xVziviM2257>8
/z: y$)5i)/=w3#/4M(x:$$+i>$*et33JY
6
9?80sW72/YP1e=+CVSP7Jx(/1)0$;+m]_0
[h3j:3JS9x['F=D+)x# F*[25!J3eIV(==5Q
%n/h*74h>21;-,\SP:12P73xP'/S*0.p)6
Z
[?#<2:3js9X['f=d+)J#+h/1:)Jj+>[$\l
svP#9Ey)$j$=R[g0H;w72/yp1E>j5x)zB5PCu257$8
/>'12'$vH(5lL86riM9Ey)$j$=F%25!jup//(==Uq
%:%h$)5I)/=W3#/4>UXf9h5+'Q;:$j++e$uYT33jy
kGs5B#o):j:G5% Qi/)$X#4h'*e)$<63$z
0
N|\) 9eY)$J$=r[G0hVW(E1:P<Jpe/JI [
gIcUXf9h5+'Qiz.<VI:3JS9x['J_32s!R4>'%(==5Q
%:%S$)5I)/=W3#/4>:X33+DK;*[25!;+#2257I8
/z:%+$)5i)/=w3#/4>:x:$=+uM'hVt33HY
6
9?80sW72/YP1e=+CVS07Jx(/1h)IRjw]_0
[h-h:3JS9x['F=D+)<#O):J:g5Hp:(BE7>u)*[*0
[h-j:3JS9x['F=D+)<#O):J:g5H+:2BY*j5l9! vL
s2iCsxF9H5+'qIZ.<v4:/xsz=U+)i257i8
q
5&[(J74h>21;-,\SP:J2P!J+(:1E(E-tT6
>S5E#O):J:g5% qI/Y$)5I)/=W8b#UH'%)7><632Z
aAH;+:3js9X['f=d+)$#+:[bV(HUi9! yl
[
,?+*72'=J,wQiz.>-l:/B:Pxyj#/ E6d8
/>u 2'=j,WqIZ.>-L:_KD:7YX3i/s*0.P)6
>!)j-W7[1E(5% qS%v$x#hHUVtP=<63$Z
0
N|\) 9ehPEu'F=Dv5E#+H/1:9<y,#[$\L
sv3M9EHpeU'f=dV5e#>jm620!;4E2257$8
/z:Us$)3+#$lL86Yu#9127!-33u257$8
q
5&[(J74p((*W3#/lm/X:ZxJ+wI/h)h*[y
k/)074P((*w3#/LM/xX+m'w)eUHpH3)*[j0
[h;h:3 :;Ie=+CH)P7')+r.A$b+Ue2H)T33jy
kGsSi#o3/fT-,\sEu12p73X(/%)00.P)6
Z
[?#<2:3 :;iE=+ch)77jX(/1y)HUip]_0
[h;l:3 :;Ie=+CH)77')+r.A$j+Im2u)T33jy
kGsSe#o3/fT-,\sEu 2p75X3/UV50.P)6
Z
[?#<2:3 :;iE=+ch)57jX(/1T7ij,#]_0
[hV+:3 :;Ie=+CH)57B>0YX+Zx]3cU257$8
/z:/H$)3+#$lL86Y3C9125!jJW$j(==5q
y
a&Zt%#o3/hH-,\sE'h2p!j+(svs5JrTt6
>S)b#O3/Hh-,\Se'H280sS[9*-*E]jw*\h9[
gd>:u2'=Jl3Qiz.>-l:/XYZh-4wS257I8
q
5&[(J74p(S W3#/lc(X:ZxJ+):*j*.:Q
%:/S$)3+e[Ll86yU#9[(J60WPEu+*jR)*[J0
[OVIP9ehP>3'F=Dv5E#+:[Bh7hV49! YL
[
,?+*72'=Jl3Qiz.>;+:/B:Px5,#'1E6d8
/>:j2'=jL3qIZ.>;+:=2'.-#4hsUT7B<632z
aAHvJ:3 :*=E=+ch)p7jw3e +)eU)*[j0
L
F& 9XxF7XYP=R[g*J3w(e1:p$r+W[%i [
gI>SXf7xyp=r[G*j3W+*7Gg7;xmS%S90.pw6
>!)h]W7[1v75% qSuh$x#hH[Jv*I<632Z
0
N|\) 9ehP>3'F=Dvsb#+H/1:(j34P:$\L
sv4(9EHp>3'f=dVSB# 9Xd/$<+PM' Ht33HY
kGs0=#o3/hH-,\sEu%2p7-X3sUsS0.P)6
Z
[?#<2:3 s-,\s>s%2p!j+Wu1:S.:q
%:Vj$)3I=r[G)>-WJ_.3$j+hm/FhT33hy
k/+S74P>qIZ.HYu:FU20!vi#[j(==rq
%n/+)74p>Qiz.hyU:/XhZhyl(I257<8
q
5&[(J74p>Qiz.hy3:/B:P$yh>2$\L
sv4p9EH)5% Q:h)$NbV;9U-0B;L#*\H9[
gIP2Xf7he=+C/vs7H3:IBS7xy39! +L
s2ip$xF7HE=+c/VS7jw3e :7JY)*[v0
L
F& 9XxF7JE=+c/V57jX(/jV)iYJ2Jz
a)<Yw7[Uw3#/iE'xZt%/F:'b+S$]39! yl
sv4#9EHS5% Q:hJ$/;wpe/+0<;)*[v0
[OVh(9ehs5% q:Hj$x#pH[uv9<<63IZ
0
N|\) 9ehs5% q:H)$x++($%t5jVtT6
>S9=#O3ULl86Vlm9[(J60WmEFE7x3)*[J0
[h5U:3 )-,\S>Su2Dj#4H:1+5I<63IZ
aAH53:3 )-,\s>sU2p73X>2*e(0.Pp6
Z
[l
F##+B7;8s<w<*>'hm\q
56
e78+3'7O[280sS'9[lT##Y<bD7w79K<C8d$#g*qMDU.\[/:5P*P!-lcUHS67[K-/Bj*b;l>]Xlyx+Uw0Xz:9q+H/Vt5EuW+YP*P!J4w'Ft$.D(>EJE)h$W2baSZ$]I>0X4yb+Uc0Z
Fh#9P=3Mi-)KP:=2'.1# f*[2<sGTOc8D$+G/2%d7W7*/Ac.g/6K$%9= YX++)(1s5.#$<)1-p$]+>'$23_jXC$4288z((e1+9X;H:=6 YX++p21)97*;-[bJSHv!:]0*7!-3>:42,_3X3[40
'4\Y3QeO65493l%280sS'9[lT##Y%K$ .4TW6K>IV6cv:]>>.M/KqO=A$1D((E1Y;xVU29=Uyx+p>[ E5.#=-/Bj(r# ;ba:Z=3IP(V288D((E1+9x;h:]P*7!-3>:4269qUH:*S)r#M-[Bh7r8
o!=-H-)KT=3MHCJ# 9Xd;$#%)+9-a[.ds!mxP[s*;Qw.26shs0c0g>1Gw'%A:zX5,(:%i$1z((e1y;Xvu29I*p!-Jr9[3/_jX(ij:S$# ;%A:zXrH(uj26yQPh'Us)R#T<) -5Jvir9C*7!3Pr6
e78+3'7O$W'\3z>9[(J6[W+r2z$+g/2%D7w79/%]PGHM#t%fDd.9/9'KX;V_Jx(2F:)b*W'ba:Z=Vp3(%I$,q+H'*M$#'K-/Bh7hR,P9[3V_Jx(IJ:s$#to) -5jVIR9$Uyb+Iw:/M$UqpH[ ML
)C 6'lF>##59=ID[7\59=xP/9/#09-u/6CV:=>>.m/kQo=a$1d((e%V5JYi29=uYX+uE'UV).#=-/bJ(R# ;BA:zXrJC(*288d((e1+(B]J:]p*)!5,>:4269Qih2fs)R#m-'bJ5R8
o!=-J-)KT=3MH$8< fm>288< :\>a6y/#09-a[.ds!mxi[//VQBdoGs#$O)1-p$]+>'$2G9Q+h/jepH-T:RA:zBU!:=6uYX++p21)97\5O)1-p<5+M2xiv_3XCu/s\7*k-[bJSHv!:DAHz=3!Y
38Z<BEoU]lF>=Iu:y2Z3mGw+y2Z$+G/2%d7W79/%]pghm#T%FdD.9/9'kx;v_jX(2f:)B*w'BA:z=vP3(%i$,Q+h'*m$#'k-/bH7Hr,p9[3v_jX(ij:S$#TO) -5Jvir9$uYB+iW:/m$uQPh[ ml
)C 6'lF>.EoU[')$8< fm>288< :\>a6y/#09-a[.ds!mxi[//VQBdoGs#$O)1-p$]+>'$2G9Q+h[/H7e-T:RA:zBU!:=6uYX+P3:ve07\5O)1-p<5+M2xiv_3XCu/s\7*k-'bs(Hv!:DAHz=3!Y
38Z<BEoU]lF>=Ii:y2Z3mGw+y2Z$+G/2%d7W79/%]pghm#T%FdD.9/9'kx;v_jX(2f:)B*w'BA:zX5,(:%i$,Q+h'*m$#'k-/b:0$j3)9[3v_jX(ij:S$#TO) -5Jvir9$uY=+uM:/m$uQPh[ ml
)K2M9;)$NbV;9-u/6CV:\0u.4tw+k;gW6zsU5>2GyQ+hu/+0B3T:50*p!U+)ify67%((e/e\7\5<)1-pB-L#sxZ:yQ+h/ H7eUw2%A+z$U,>0xi/_3Phujs)R#m-ib+0<$q
7O7)cb#*m9kxw8#Y<bD7w79K<C8d$#g*qMDU.\[/:5P*P!;IPI%h67[K-/BtP$R,)]Xlyx+I#0Xz:9q+H/%j*EyW+YP*P!Jp3[Ft$.D(PEJt;h$W2bah7!;h>:42,_RxPIVML
)K2>qEo77GVUoID[7\) c=2<sGTOc8D$+G/2%d7W7*/Ac.g/6K$%9= Y=+i3u e5.#$<)1-9e3+>'$23_jXC$4288z((e1:0<],:=6 YX++3[/s;7*;-'%-)ivir9$uY=3XCu/s\7x(3[bH7R8
oUX/w'\3ZC9>D>\%V%9[(j6[w6k>iv6CV:\>a6y/#09$ad6ts<cM;[7[;-[bs7J3,C]x;/_jX)( :)B*wf)1-5i$w+y0*p!j+pife$#';-/b:7=vi#9$ YB-X>$/s\7*k-[ -5Jvir9C*7=+P30z
3'8['7y0ap745'q[(j6'k%/xL<yz#+9 -pX<6(sx8z\t;9RAu[\juY
yE3G545<k 2'8['+*7g:9GP:R- /4\w3e1:t3jL:ZboWy<=-B>opB8
57y=w'8z/C9E3G5\) c6u[B#=6%07873X(/25p>#cho. t,Qk%o1Jl
845'qE3/s;w7y=w80Ss;B>)$,9;<w[27!j+9!1V$(+90%2LY9G9('z
[:)'$=36uWX#o;5lZt%/5<m123+dk!=xHzXj)$[122!KVO*I*/mK+C6
93'8['7Y0d7745'Q[(J6'K0[Xl<YZ#+9 -Px<_3/X8Z\T;9raUw\JUy
36F:1Eo;[xF:1E 9Xd3/mjw;]=2<9zs!mx3.utwfyA)z>]+(/1m$u'(Ceh:pXj+r952:_3HMef)9[
457Y=W'83;:36;-#<2qY0dP7't'9-U/6cv:YDd87%5-UBv;xJ+(0X4:_-xe/1:Px$Ws96*7$;x#UJ0
'845'Qe35745'Q[(J6'K0[X361#Y<bD7w7'SiMXl:_;xe(1:Px$WiYajZ>J+(/1M$(#5-[J)ZE;hy
36F:1Eo;'p2'8['+*7g:9tP:y$;$+zkQw.2:6t :R6*S!Y,(/1:\7x5-'bVpXj+(0x8$8QP)ubeS$8
o;36;-)'3:36;-#<2Qy0ap7'T'9-u/6CV:yd4W7%5-:b)(Xj+(0x4:_-XE/1:pX$wS96*7>vX32/0
'845'Qe3sY#O;5LzT%/5<K12:.[W6b0GHM#5qM[238qIHU*:PxJ!:d6*5!y+(/1:\7(W;) v)!3h>6
e3'8['7Y/2'8['+*7G:9gp:Y$;$+ZKqW.2:6Xv:r6*)!;j(/1:\7X5-'BvPxJ+(0X8$8qpe:Bh9h8
o;36;-)'iO9E3G5\) c6u[=#525xP/9/#096gW##=;)/-Sij+(/42,8Quhs1:pXj!:Zx3Y=Yih[jsl
)'o;5lF:<#o;5lZt%/5<k%2:.[w6B0ghm#5QD.238Q3hsh:pXj!:D6*5!Y+(/1:\7(w;) yS!rP>6
e3'8['7YV $)'$==2'.8Z/c96Ig79K<C8d$8/v+9i3yj+le/1:Pr#M;)%-*xJ+(/4227'(32u-0=VQ
7Ye3g545)9e3g5\) C6U[j#525Xp/9/#096G,M#=;)/-)>J+(/42,8qIH:H:PxJ!:zX3y=3ly
36F:1Eo;2p2'8['+*7g:9G3:y$;$+zkQw.2:6t :R6*)!vL(/1:\7x5-:bs*Xj+(0x8$8QP3sz
F:)'$=36T$,9;<w[2+N2w6B0ghm#5QD.238Q4h21:pXj!:D6*5!Y+(/1:\7(w;)%)9[
457Y=W'8u;:r- /4\WJ_g2<9ZS!MX3.M\WFYa+Z$J+(/1M$U'(cEH:PxJ+R952:_-3)6
6f:-eO;b>:$)'f==2'.8Z/(9ipV9c '9 -Px<6(SX8Z\T;9raU[\JUy
yE3x545<k 2'80'+*7g:9GP:R- /4\$:[b:p0.+E95->md)f)0a>X-q
;36/-)'K%'Xf:-e 9xD3/S-WF\PUH#[W3E1:T3Jl:zBOwY<=-b>OPb8
57y3w'8z/M9E3x5\) c6u[J#=6%0781#Ph/1(=XYwSeMDv0%(<kM:5[
,57Y3W'8Zv(9e3X5\) C6Uwx#=6%0781#pH/1(o=JWsEmdV0%(<Mm:5[
,57Y3W'8Zv39e3X5\) C6Uw=#=6%0781#pH/1(o=JWsEmdV0%(<Mm:5[
457Y3W'83W7Y3W80sS;b.:$.'f:\0U.4TW;Ccd$,'(mEHEPxJ+R9c3yb+l(/1:Pr#C:Yah9j+,m2Z
F:)'F=36Hv745[q[(j6'k0/xi:-#y<Bd7W7's0=xL:_;XE(1:pX$wIyAJz>j+(/1m$(#5-[j)ze;HY
36F:-Eo;'xF:-E 9Xd3/m3w2y32<9zs!mx3.utwfyA)z>]+(/1m$u'(Ceh:pXj+r952:_3HMef)9[
457Y3W'8-;:36/-#<2qY0d77*5[9-U/6cv:YDd87%5-UBv;xJ+(0X4:_-xe/1:Px$Ws96*7$;x#UJ0
'845[Qe3s745[Q[(J6'K%/XI:-#Y<bD7w7'SiMXl:_Vxm$1:Px$WiYajZ>J+(/1M$(#5-[HSZ=5Iy
36F:-Eo;up2'80'+*7g:9G+:]6/$+zkQw.2:6t :R6*)!;J(/1:\7x5-'bVpXj+(0x8$8QPE:bH9H8
o;36/-)'i:36/-#<2Qy0a77*5[9-u/6CV:yd4W7%5-:b)(Xj+(0x4:_-XE/1:pX$wS96*7>vX32/0
'845[Qe3)Y#O;-LzT%/5<K 2680W6b0GHM#5qM[238qIHU*:PxJ!:d6*5!y+(/1:\7(W;) v)!3h>6
e3'80'7YV2'80'+*7G:9gU:]6/$+ZKqW.2:6Xv:r6*s!yl(/1:\7X5-'BvPxJ+(0X8$8qp)UB+7h8
o;36/-)'4O9E3x5\) c6u[B#T;-xP/9/#096gW##=;)U-*>j+(/42,8Quhs1:pXj!:Zx3Y=53hi sl
)'o;-lF:$#o;-lZt%/5<kU2680w6B0ghm#5QD.238Qih:h:pXj!:D6*)!vL(/1:\7(w;) H*[
457Y3W'85;:36/-#<2qY0As7*5[9-U/6cv:YDd87%5-:BS*xJ+(0X4:_Vx>S1:Px$Ws96*7=yQ
7Ye3X545w9ipV9c '9kxT79K<C8d$8/M09i3y<+h(/1:Pr#M;)%-*xJ+(/4227'(cUJ0
'845[Qe3(Y#=6%0781#>J*Xp/9/#096Gw##=;)V-9xJ+(/42,8qUHS1:PxJ!:zX3yb;hy
3Uw'\313+lFp54939;)$#<2Q-x361#y%k$;vX2s!mxi[//VQBdoGs#$O)%-;JjHEs$2G9Quh(U:9>YT:RA:zBU!:=6uYX++(ivJp7\5O)1-pXr4C/xiv_vHhuUs)R#T<)/yzJ;i>0x4YB;X(:40
'jeOu[Rj%54+=3mh$/;W+*7GX7't'9-A[.[;(nD7w7*/aC.G/6k$%9= yb+,m/Jv*.#$<)%-;jJheS$23_Jxc$4288Z((E1:0<-+:=6 yx++(IVjP7*;-:J-sjVIR9$Uyh5xmU/S\7X(cUB:)r8
oMqEo7w;e=31w'\3wAuxZt%/F:y$;$+G/25p:A6CV:]>>.m/kQo=a$1d(Cef)p$YL29=uYB+,M/jV*.#=-/bJ(R# ;BA:zXj4p'1288d((e1:0<-+:]p*)$+3M:/m$.z(>2b)SHv!:DAJS!jir6
e)-)kp_:)W'xeOu[X>s7\) C32:.[W6K>IgYJdqW.26SHS0C0G>1gW'%ajZE;+)SHI$1Z(cEF)P$yl29i*P!-jR9[3/_Jx(/V+5x# ;%a:ZxJ4P'126YqI)Eu))h$W2baS9!;3>:42,_-3H//ML
);'7o c0PEo(qEo77h3:=2'.-#525xP[s*$O/Gghm#T%FdD.9/9'kx;v_-X#u1y*>*w'BAJze;+)shi$,Q+h'*m$#'k-/b:p<ru(9[3v_jX(/v+5X#TO)/yzJ;i>0xi/_vHhuUs)R#m-'U-pH$q
7ULf>=mhVQe:-)kp:fu280sS[96Ig79/%]= PO/#09$AD6TS<Cm;[7[;-'BEsx5le]X;/_-x#U1Y*>*WF)1-5I$W+Y0*P!J+PI%:$#';-/B:P<RU(9$ yh5xmU/S\7*K-:J-sjVIR9c*5j++>0Z
FS5493H*q-)j'7o 2dJ# 9Xd/$8*$:\>a61d+zc8D$.G*Qmdu.\[/:5p*5!]3(2hV67[k-'beSX5LE]xLYX+uW0xZ:9Q+h/1+0Bjw+yp*p!j+pi%:$.d(>2b)SHv!:]0*)$+3M:/m$uQuMe1s\[
43=3mh#>1'7/Lf>=#*m9[(J60W;]=2<Sgt'%1!.4TW2K;Gw6ZSu5>2gYqUH(u:9>yt:50*5!]3(2Hv67%((E%t\7\5<)1-PxR4c/Xz:Yq+H/1+0bJW2%aS9!;3>:4269qI)Eu))h$Wi)%)ZxV!y
3Uw'\31#+lFp54939;)$#<2Q-x361#y%k$;vX2s!mxi[//VQBdoGs#$O)%-;JjHEs$2G9Quh(U:9>YT:RA:zBU!:=6uYX++(ivJp7\5O)1-pXr4C/xiv_vHhuUs)R#T<)/yzJ;i>0x4YB;X(:40
'jeOu[RhPpeO(QeO77H3:=2'.-#525Xp[S*$o/gGHM#t%fDd.9/9'KX;V_-x#U1Y*>*W'bajZE;+)SHI$,q+H'*M$#'K-/B:P<RU(9[3V_Jx(/V+5x#to)/YZj;I>0XI/_VhHUuS)r#M-'u-Ph$Q
7:Lf>=mpVQe:-)kp:fu2+nT5:]6/$+g/25P)a6cv:]>>.M/KqO=A$1D(cEF)P$yl29=Uyb+,m/Jv*.#=-/Bj(r# ;ba:ZxJ4P'1288D((E1:0<-+:]P*)$+3m:/M$.Z(>2B)shV!:dajs!JIR6
eS-)kp_')W'xeOu[X>s7B>0YXI:-#Y%K$;Vj2S!MXI[//vqbDOgS#$o)%-;jJheS$2g9qUH(u:9>yt:ra:Zbu!:=6Uyx++(IVjP7\5o)1-PxR4c/XIV_VhHUuS)r#t<)/YZj;I>0X4yb;x(:40
'heOu[R)%54+=3mh$/;WJ_.3$.'f:\>A61D3ZC8d$.g*qMDU.\[/:5P*5!]3(2Hv67[K-'BEsx5le]Xlyx+Uw0Xz:9q+H/1+0bJW+YP*P!J+PI%:$.D(>2B)shV!:]0*)$+3m:/M$UqUmE1S\[
4I=3mh#h1'7/Lf>=#*m9kxw8#t;-Xp[S*$oUgGHM#t%fDd.9/9'KX;V_-x#U1Y*>*W'bajZE;+)SHI$,q+H'*M$#'K-/B:P<RU(9[3V_Jx(/V+5x#to)/YZj;I>0XI/_VhHUuS)r#M-'u-Ph$Q
7:Lf>=m4VQe:-)kp:fu2+nT5:]6/$+g/25P)a6cv:]>>.M/KqO=A$1D(cEF)P$yl29=Uyb+,m/Jv*.#=-/Bj(r# ;ba:ZxJ4P'1288D((E1:0<-+:]P*)$+3m:/M$.Z(>2B)shV!:dajs!JIR6
eS-)kp_2)W'xeOu[X>s7B>0YXI:-#Y%K$;Vj2S!MXI[//vqbDOgS#$o)%-;jJheS$2g9qUH(u:9>yt:ra:Zbu!:=6Uyx++(IVjP7\5o)1-PxR4c/XIV_VhHUuS)r#t<)/YZj;I>0X4yb;x(:40
'heOu[Rt%54+=3mh$/;WJ_.3$.'f:\>A61D3ZC8d$.g*qMDU.\[/:5P*5!]3(2Hv67[K-'BEsx5le]Xlyx+Uw0Xz:9q+H/1+0bJW+YP*P!J+PI%:$.D(>2B)shV!:]0*)$+3m:/M$UqUmE1S\[
4I=3mh#>1'7/Lf>=#*m9kxw8#t;-Xp[S*$oUgGHM#t%fDd.9/9'KX;V_-x#U1Y*>*W'bajZE;+)SHI$,q+H'*M$#'K-/B:P<RU(9[3V_Jx(/V+5x#to)/YZj;I>0XI/_VhHUuS)r#M-'u-Ph$Q
7:Lf>=m,VQe:-)kp:fu2+nT5:]6/$+g/25P)a6cv:]>>.M/KqO=A$1D(cEF)P$yl29=Uyb+,m/Jv*.#=-/Bj(r# ;ba:ZxJ4P'1288D((E1:0<-+:]P*)$+3m:/M$.Z(>2B)shV!:dajs!JIR6
eS-)kp_[1Q-)J'7O 2Dj#>JM62680W6K>IgY;dqW.26SHS0C0G>1gW'%ajZE;+)SHI$1Z(cEF)P$yl29i*P!-jR9[3/_Jx(/V+5x# ;%a:ZxJ4P'126YqI)Eu))h$W2baS9!;3>:42,_-3H//ML
)U'7o c7PEoU[x361# 9Xd;$st9UR.a$+zkQw.28shs0c0g:.tsU5>238Q+h2x;v_]X3sUT)H*w'BAHz>3+#:/i$,Q+h'*m$#'k-/b:7J5i)9[3v_jX(2fJpB#TO) )z=3i>0xi/_3PhsUs)R#m-[ -0B$q
7$Lf>=mUVQeO77't'9[(J6[W%MmO3MgW6b0GHM# %fDd.9/52MDOgS#=;)1-97[;-(Bh*juI>]X;/_3xe[1E)h*WF)1-5I$W+Y0*P!Jpm2/Y$#';-/B:9E-+c9$ y=;x3[/S\7*K-[ -*jVIR9c*7=+4c0Z
F(5493HUq-)KP:y$;$#<2Q5xaW\K=0kxP/9/#09[ad6ts<c6iW6K$%9I3YX+H:5p*;!3LM$/s67[k-[bV7X]i>]xLYX+uW0xZ:9Q+h/ )9H5w+yp*p!jH#'1J$.d(3ubH7Hv!:]0*5J+3p:/m$uQP3evJ\[
4j=3mh#h1'7O 2:.[W+*7Gg7gvuOid[79K<C8d$#g*qMDU.8*vqO=A$,'((EJ2gYq,H[H)(hVt:50*7!yp((/S67%((E%t\7\5<)1-P=;h>2Xz:Yq+H/JE5x-W2%ahs!3p>:4269qp3EH))h$Wi) hZ<-!y
3*w'\31p+lF>=#525xZt%/$:k.o>,t/:\0u.4tw+k;gW6zs;].g>1GwfyA:z$#$O)f-7>;J>:$2G9QPhs :;HvT:RA:zBU!:=6uYX++3ujs97\5O)1-p$]u('xiv_33h[ s)R#T<) Hz>;i>0x4Y=3Xp'40
'IeOu[RY%549396Ig7\) C=2[Mk9FM>2<9ZS!MXz[//vqbD36M/9'KXl:_Jx)9= yE+peU*S).#$<) -*=J,>:$23_Jxc$4288Z((E1hs$Vh:=6 yx++)(%:57*;-[u-7=VIR9$Uy=3xeU/S\7X(3[B+5r8
oWqEo7wUe=3MH$8*$:=2'.1#/0oMLWs#y<Bd7W7\/Ac.g/6'T0cM;[7%5-/by$1d(#e VSivi29=uY=+L3/fs).#=-/bJ(R# ;BA:zX33):j288d((e1y;Bju:]p*7J+P3:/m$.z(3[bVSHv!:DAH7!rur6
et-)kp_S)W'\3W;]=280sS'9>d>\%v%9-U/6cv:=>>.M/KqY$d.\[/:r6*P!5W'%aEZ=y3w:/I$1Z(3EHhPEVI29i*P!-jR9[3/_Jx([uY)$# ;%a:Zx5,c/%26YqpmE h)h$W2bajs!;4>:42,_3pHI%ML
)U'7o c;PEoU[x361# 9Xd;$st9UR.a$+zkQw.28shs0c0g:.tsU5>238Q+h2x;v_]X3sUT)H*w'BAHz>3+#:/i$,Q+h'*m$#'k-/b:7J5i)9[3v_jX(2fJpB#TO) )z=3i>0xi/_3PhsUs)R#m-[ -0B$q
7$Lf>=mp(+Lf>=#525XzT%/$:K.O>,T/:\0U.4TW+K;Gw6ZS;].G>1gWFYa:Z$#$o)F-7>;j>:$2g9qpHS :;hVt:ra:Zbu!:=6Uyx++3UJS97\5o)1-P$]U('XIV_33H[ S)r#t<) hZ>;I>0X4y=3xP'40
'>eOu[Rh%54939$3X7')+r.A$ST9ur.A$+ZKqW.28SHS0C0G:.TSu5>238q+H2X;V_]x3Sut)h*W'bahZ>3+#:/I$,q+H'*M$#'K-/B:7j5I)9[3V_Jx(2FjPb#to) )Z=3I>0XI/_3pHSuS)r#M-[ -0b$Q
7SLf>=mUVQeO77*5[96(8,T/:K.O>,T/:\0U.4TW+K;Gw6ZS;].G>1gWFYa:Z$#$o)F-7>;j>:$2g9qpHS :;hVt:ra:Zbu!:=6Uyx++3UJS97\5o)1-P$]U('XIV_33H[ S)r#t<) hZ>;I>0X4y=3xP'40
'>eOu[R)%54939$3X7')+r.A$ST9ur.A$+ZKqW.28SHS0C0G:.TSu5>238q+H2X;V_]x3Sut)h*W'bahZ>3+#:/I$,q+H'*M$#'K-/B:7j5I)9[3V_Jx(2FjPb#to) )Z=3I>0XI/_-3HUVS)r#M-[ -0b$Q
7SLf>=mIVQeO77*5[96(8,T/:K.O>,T/:\0U.4TW+K;Gw6ZS;].G>1gWFYa:Z$#$o)F-7>;j>:$2g9qpHS :;hVt:ra:Zbu!:=6Uyx++3UJS97\5o)1-P$]U('XIV_33H[ S)r#t<) hZ>;I>0X4y=3xP'40
'>eOu[R+%54939$3X7')+r.A$ST9ur.A$+ZKqW.28SHS0C0G:.TSu5>238q+H2X;V_]x3Sut)h*W'bahZ>3+#:/I$,q+H'*M$#'K-/B:7j5I)9[3V_Jx(2FjPb#to) )Z=3I>0XI/_3pHSuS)r#M-[ -0b$Q
7SLf>=mhVQeO77*5[96(8,T/:K.O>,T/:\0U.4TW+K;Gw6ZS;].G>1gWFYa:Z$#$o)F-7>;j>:$2g9qpHS :;hVt:ra:Zbu!:=6Uyx++3UJS97\5o)1-P$]U('XIV_33H[ S)r#t<) hZ>;I>0X4y=3xP'40
'>eOu[Rt%54939$3X7')+r.A$ST9ur.A$+ZKqW.28SHS0C0G:.TSu5>238q+H2X;V_]x3Sut)h*W'bahZ>3+#:/I$,q+H'*M$#'K-/B:7j5I)9[3V_Jx(2FjPb#to) )Z=3I>0XI/_3pHSuS)r#M-[ -0b$Q
7SLf>=mlVQeO77*5[96(8,T/:K.O>,T/:\0U.4TW+K;Gw6ZS;].G>1gWFYa:Z$#$o)F-7>;j>:$2g9qpHS :;hVt:ra:Zbu!:=6Uyx++3UJS97\5o)1-P$]U('XIV_33H[ S)r#t<)%)ZjRI>0X4y=3xP'40
'>eOu[RE%54939$3X7')+r.A$ST9ur.A$+ZKqW.28SHS0C0G:.TSu5>238q+H2X;V_]x3Sut)h*W'bahZ>3+#:/I$,q+H'*M$#'K-/B:7j5I)9[3V_Jx(2FjPb#to) )Z=3I>0XI/_3pHSuS)r#M-[ -0b$Q
7SLf>=mp(+Lf>=#t;-X3T#%v%9>d>\%v%9-U/6cv:=>>.M/KqY$d.\[/:r6*P!5W'%aEZ=y3w:/I$1Z(3EHhPEVI29i*P!-jR9[3/_Jx([uY)$# ;%a:Zx5,c/%26YqpmE h)h$W2bah7!y3>:42,_3pHI%ML
)33=3MH#=1'7/lF>=#*M9[(j60wj_G2<sGT'%1!.4tw2k;gW6zsU5>2GyQuh(U:9>YT:50*5!]3(2hV67%((e%T\7\5<)1-pXr4C/xZ:yQ+h/1+0Bjw2%As9!;3>:4269Qi)eU))H$wI)%)zXv!Y
3 )-)KP_')w'XEoU[x>S7\) c32+N2w6k>iGyjDQw.26shs0c0g>1Gw'%AJze;+)shi$1z(Cef)p$YL29I*p!-Jr9[3/_jX(/v+5X# ;%A:zXj4p'126yQi)eU))H$w2BAs9!;3>:42,_-3h//ml
)3i=3MH#=1'7/lF>=#*M9KXW8#>j*xP[s*$OuGghm#T%FdD.9/9'kx;v_-X#u1y*>*w'BAJze;+)shi$,Q+h'*m$#'k-/b:p<ru(9[3v_jX(/v+5X#TO)/yzJ;i>0xi/_vHhuUs)R#m-'U-pH$q
7[/W'\31c+LfP54939;)$nBv;9kxT79/%]= sO/#09$AD6TS<Cm;[7[;-'BEsx5le]X;/_-x#U1Y*>*WF)1-5I$W+Y0*P!J+PI%:$#';-/B:P<RU(9$ yh5xmU/S\7*K-:J-sjVIR9c*5j++>0Z
F7XYP=38Z<iEoU=xZt%/F:=2'.1#y<Bd7W79k<c8D$#G*Qmdu.\[/:5p*p!-LCuhs67[k-/bJ*B;L>]xLYX+uW0xZ:9Q+h/vT5eUw+yp*p!j4W'fT$.d(>eje)H$w2BAsz$]i>0x4YB+uC0z
F7XYP=38Z<iEoU]lF>=# 9Xd/$#<2Q5xP[s*$O/Gghm#y%k$;vX2s!mxi[//VQBdoGs#$O)1-5>-3E:$2G9Q+h[UVp>vT:RA:zBU!:=6uYX++Cs1H*7\5O)1-p<Uu#$xiv_vX)(/s\7*k-'b))Hv!:DAJzB-!Y
3 :*=Eo!=-T-)KT=3MHCB# 9Xd/$#<2Q5xP[s*$O/Gghm#y%k$;vX2s!mxi[//VQBdoGs#$O)1-5>-3E:$2G9Q+h[UVp>vT:RA:zBU!:=6uYX++Cs1H*7\5O)1-p<Uu#$xiv_vX)(/s\7*k-'b))Hv!:DAJzB-!Y
3 :*=EoUX H-)KP:=2'.-# Am7u[gS+:\>a61d+zc8D$+G/25p:A6CV:]>>.m/kQo=a$1d((e%H5H-i29=uYX+P(uhT).#=-/bJ(R# ;BA:zX;JC:v288d((e1T9=5J:]p*S!r,>:4269QPh$fs)R#m-[by(R8
o3/hH-)K23[lF>=Iu:=2'.-# Am7u[gS+:\>a61d+zc8D$+G/25p:A6CV:]>>.m/kQo=a$1d((e%H5H-i29=uYX+P(uhT).#=-/bJ(R# ;BA:zX;JC:v288d((e1T9=5J:]p*S!r,>:4269QPh$fs)R#m-[by(R8
o3/fT-)C 6$lF>##>jm62:0\=0kxP/9/#09-u/6CV:=>>.m/kQo=a$1d((e%V5JYi29=uYX+uE'UV).#=-/bJ(R# ;BA:zXrJC(*288d((e1+(B]J:]p*)!5,>:4269Qih2fs)R#m-'bJ5R8
o3/fT-)C 6$lF>.EoU[xX+m'w;*[LWs#y%k$;vJ2s!mxP[s*$OuGghm#T%FdD.9/9'kx;v_jXCs%)*H*w'BA:z=;L(s/i$,Q+h'*m$#'k-/b:5>jPE9[3v_jX(i*J;i#TO)/-9evir9$uYB+3>:/m$uQuh'%ml
)3+#$lFh#9J=3Mi-)KP]'xX+m'w;*[LWs#y%k$;vJ2s!mxP[s*$OuGghm#T%FdD.9/9'kx;v_jXCs%)*H*w'BA:z=;L(s/i$,Q+h'*m$#'k-/b:5>jPE9[3v_jX(i*J;i#TO)/-9evir9$uYB+3>:/m$uQuh'%ml
)3+#$lF>%3P=3MH$NbV;9[>W%z/.X 2<sGT'%U!.4tw6k>iGy;DQw.26shs0c0g>1Gw'%A:zB3u>'/i$1z((e :S>Ui29I*p!-Jr9[3/_jX(u*J)<# ;%A:zXUH32*26yQ3hifs)R#T<) -(evir9C*7!5Jr6
ehPEu'7O7h75493l%2+nT5:=;dJ9g\ [Xp[S*$oUgGHM#Y%K$;Vj2S!MXI[//vqbDOgS#$o)1-5=-Ic:$2g9q+H[1)*IVt:ra:Zbu!:=6Uyx++m$%S07\5o)1-PI5p)$XIV_;xP(/S\7*K-[Bt;hV!:dahZ$u!y
3js9X['7Nhw'\\w+R2Z$)5i)/=w8B#y<B[ghm#y<Bd7W7\/Ac.g/6K$%9= YX++p[f)(.#$<)1-7X5u3'$23_jXC$4288z((e +5J;H:=6 YX++W:/e77*;-/be0ev!:]0*7!]u>:42,_jXEuvml
)5i)/=w'oY'7o[_57\=9=xF9H5+'q[J$+zk+c8D$+zkQw.28shs0c0g>1Gw'%A:zXrP#u*i$1z((e :9B3u29I*p!-Jr9[3/_jX3i%)S$# ;%A:zXUi>( 26yQ+h(ve)R#T<) -;Bvir9C*p!Y3p0z
F9H5+'qE!*5492qEo77\=9=xF9H5+'q[J$+G/2%d7W79/%]pghm#T%FdD.9/9'kx;v_jX(2f:)B*w'BA:zX5,(:%i$,Q+h'*m$#'k-/b:0$j3)9[3v_jX(ij:S$#TO) -5Jvir9$uY=+uM:/m$uQPh[ ml
)5i)/=w'oY'7o$w'\3ZC9[Lt##o):j:G5\u:\>a6y/#09-a[.ds!mxi[//VQBdoGs#$O)1-p$]+>'$2G9Q+h/*e*B;T:RA:zBU!:=6uYX++):*V97\5O)1-p<5+M2xiv_3XCu/s\7*k-[b)(J;Jr9C*7!3Pr6
eY)$J$=3gv-)kt=3mhcj# F*[2'$Vh(5Lz579/%]PGHM#Y%K$ .4TW2K;Gw6ZSu5>2gYq+H[/h7E-t:50*P!Jh#//j67%((E%t\7\5<)1-P<5+m2Xz:Yq+H[ S0ERW2%ajZhuI>0XI/_3xcU/S\7X(3E h\[
4h>21;-)k2(QeO774h>21;-nBf:3JS9x['a[Xp[S*;qW.2<SgtoC8d$.g*qMDU.\[/:5P*P!3,(S$2g9q+H/F)s.#=-/Bj(r# ;ba:ZxVp>2*288D((E1v)>J+:]P*s!-4>:4269qpH2%S)r#M-[B+\[
4h>21;-)k23QeO774h>21;-nB$:3JS9x['a'Xp[S*;qW.2<SgtoC8d$.g*qMDU.\[/:5P*P!3,(S$2g9q+H/F)s.#=-/Bj(r# ;ba:ZxVp>2*288D((E1v)>J+:]P*s!-4>:4269qpH2%S)r#M-[B+\[
4h>21;-)k2c9eY)$J$=f%2:,9;<Y2z$)5I)/=WJ%3W6b0GHM# %fDd.#/9'KX;V_Jx3'*vs$*W'ba:Z=-jeUJI$,qpH'4288Z((E j9<5j:=6 yx+pc2VY(7*;-'Bj9hV!:]0*5!-h>:42,_3x(/VML
)5i)/=w'\S3=3MH$)5i)/=wdB#5f\pu:0\w72/yp1E>j-xP[s*;Qw.26shs0c0g>1Gw'%A:zX53)]x;/_jX(2Uy67%((e%T\7\5<)1-5<vi(/xZ:yQ+h'vs)Xjw2%AHzBri>0xi/_3XCi/s\7x((evml
)5i)/=w'\Si=3MH$)5i)/=wd=#o):j:G5h+:3js9X['j_=2<sGTOc8D$.G*Qmdu.\[/:5p*p!jHM2$2G9Q+h/j)9.#=-/bJ(R# ;BA:zBri>/1288d((e%+)Hj+:]p*7!-4>:4269QPh'vs)R#m-/b+\[
4h>21;-)k2#9eY)$J$=f 2'$Vh(5L>P74h>21;-%sU:\0U.4TW+K;Gw6\Su5>2gYq+H[%t*j5t:50*P!3UwSuY67%(3E%M$#'K-/Bh5$Rhw9[3V_Jx3'J+9I#to)%-5$VIR9$Uyb+U):/M$UqpH/1+\[
4h>21;-)JW72/YP1e2 'Xf9h5+'Q;:$+ZKqW.2<9ZS!MXz[//=qbDOgS#$o)1-Pj5,w'$2g9q+H/JY5b-t:ra:Zx;4R9[3/_Jx(:H)(I# ;%a:Zx-j(/F26YqpH'u)5r#t<)%-)<;UR9c*7!3jR6
eY)$J$=31_574h>21;-%sU:3JS9x['a/Xp/9/#09-U/6cv:=>>.,/KqO=A$1D((E1)9EuU29=Uyx++)2%j5.#=-/B:s<$W+Y0*P!JIeU*t$#';-/B:5IJ+#9$ y=+UmU%M$.Z(cE/+sb$Wi) -7I$Q
72/YP1eO39eY)$J$=x7h$8%Yob6(879K<C8d$+ZKqW.28SHSFC0G>1gW'%a:Zx;h#$%I$1Z((E1Y9b-U29i*P!J3P0Xz:9q+H//vsIuW+YP*P!JUw/1E$.D(3E%)sb$W2bajZhR3c0X4y=+pw0Z
F9H5+'qEHCB#o):j:G5S2396L<yz59=xP/9/#09-u/6CV:=>>.,/kQo=a$1d((e1)9eUu29=uYX++)2%J5.#=-/b:S<$w+y0*p!jiEu*T$#';-/b:5ij+#9$ Y=+uMu%m$.z(Ce/+SB$wI) -7i$q
72/YP1eOcQeO874h>21;-/JW;r- /8< :\0U.4TW6b0GHM# %fDl.9/9'KX;V_Jx('/)s>*W'ba:Zx-ImUHI$,q+H/u+\7\5<)1-7j3hcSXz:Yq+H[uh9byW2%a:ZEu3c0XI/_Jx#$uj\7X((E/)\[
4h>21;-)-'7O$W'\3W72/YP1e*(96l<YZ59=Xp[S/#09-A[6cv:]>>.,/KqO=A$1D((E1:;E3l29=Uyx++c/*Es.#=-/B:s<$W+Y0*P!3+#SH+$#';-/B:0bVp>9$ yx+Ie/JM$.Z((EFY0$$Wi)1-)jR!y
3js9X['7'lF>.EoU['J$)5i)/=wdX#5f\pu:0\w6k>ghm#y%kd7W7*/AcIg/6K$%9= YX++((fH*.#$<)1-pBjJ#u$23_jX(uvm$#'k-/bHpeYLp9[3v_jX(i%s7H#TO)1-)>jHr9$uYX+,)ijm$uQ+h:U+\[
4h>21;-);'7O[W'\\$:3JS9x['+'X>w%Z/.x12<9Z qW.2<9ZS!MXz[//vqbDOgS#$o)1-Pj3p29=Uyx++)UJI$,q+H'*M$#'K-/Bj0hV+(9[3V_Jx3'/SPx#to)1-9bVIR9$Uy=+UP:/M$Uq+HI40
'$Vh(5Lfs549+QeO8-#O):J:g5\U:3JS9x['a'Xp/9\S!MXp/9/#09[AD6TS<Cm;[7[;-/B:s=3t:50*P!Jhm2$23_Jxc$4288Z((E%+)hJ+:=6 yx+pc:/:P7*;-/BY5hV!:]0*7!-4>:42,_JxP0Z
F9H5+'qE)-)KT=3MiG54939Ey)$j$=3Uw'\*'+/x>W%z/.X12<sGTOc8D$+G/2%d7W7*/Ac.g/6K$%9= YX++#uUi$1z((e :(>5,29I*p!-Jr9[3/_jX(:*e)B# ;%A:zXvP>2*26yQPh2%s)R#T<) -*iriM0x4Y=+4r6
eY)$J$=3uW'\*'7O$/-)kp:3JS9x['+'Xf9h5+'Q;j$)5I)/=W'jeOu]LzP79/%]PGHM#t%fDd.9/9'KX;V_Jx3(1v67[K-/B:;j;t:ra:Zbu!:=6Uyx++>[/Y(7\5o)1-P>Vl(/XIV_;xcI/S\7*K-[BY5hV!:dahZ<$Q
72/YP-eOZSLf>## ;*[2'$Vh(-Lz579K<=D7w79K<C8d$#g*qMDU.\[/:5P*P!J43(ut67[K-/BhP$-pc]Xlyx+Uw0Xz:9q+H[Vjsj5W+YP*P!Jj>:Fh$.D((EF+;h$W2bahZE-I>0X4yx+lmI40
'$Vh(-Lfa>eOu='j$#')+9eY)$Jf==%2<9Z qW.2<9ZS!MXz[//vqbDOgS#$o)1-P<3,m$$2g9q+H[1Y5=-t:ra:Zbu!:=6Uyx+pP'u)97\5o)1-PIVI#[XIV_Jx#IFS\7*K-[BE5hV!:da:Z>;4R6
eY)$Jf=3gv-)kt=3mh$#')+9eY)$Jf==%2<SgtoC8d$+g/2%D7w7*/aC.G/6k$%9= yx++)(1S5.#$<)1-P$]+>'$23_Jxc$4288Z((E1+9x;h:=6 yx++P21)97*;-[BjshV!:]0*7!-3>:42,_3x3[40
'$Vh(-Lfa>eOu]Lf>=iU:=6(874h>21/-#-W6K>IV6cv:\>A6Y/#09$AD6TS<Cm;[7[;-/B:9EJIc]X;/_Jx($Fv5j*WF)1-5I$W+Y0*P!Jh>$HY$#';-/B:0$J3)9$ y=+Um:/M$.Z(3Eutsju!:dahZ=3!y
3js9X0'7Nhw'\*'7o _S7\59=xF9H5+[q[J$+G/2%d7W79/%]pghm#T%FdD.9/9'kx;v_jX3: H;B*w'BA:zX5,(:%i$,Q+h'*m$#'k-/b:0$j3)9[3v_jX3[/+;<#TO)%-)ivir9$uY=+uM:/m$uQPh[ ml
)5i)/3w'\S+=3MH$)5i)/3w+N0w72/yp-E*39-a[.ds!mxP[s*;Qw.26shs0c0g>1Gw'%A:z=]+E]x;/_jX((U)67%((e%T\7\5<)1-pH3i)$xZ:yQ+h/hs*Xjw2%A)zBri>0xi/_3X)'/s\7x(3evml
)5i)/3w'\SP=3MH$)5i)/3w+N[w72/yp-E*C9-a[.ds!mxP[s*;Qw.26shs0c0g>1Gw'%A:z=]+E]x;/_jX((U)67%((e%T\7\5<)1-pH3i)$xZ:yQ+h/hs*Xjw2%A)zBri>0xi/_3X)'/s\7x(3evml
)5i)/3w'\Su:3js9X0'A'x33+dk;*[2'$vH(-l'j=#y<Bd7W7\/Ac.g86K$%9= YX+PC$h)9.#$<)1-7BULM2$23_3XC0xZ:9Q+h[%y0$Uw+yp*p!3u)ijT$.d(Ce%y)H$w2BAJzB5i>0x4Y=++(i40
'$Vh(-Lf>%;'7O 2'$Vh(-L>57'=6%03T##O):J:X5B>[9-A[.DS!MXI[//vqbDOgS#$o)1-P$;h29=Uyx++)UJI$,q+H'*M$#'K-/Bj0hV+(9[3V_JxcI/SPx#to) -5<VIR9$Uy=+UP:/M$Uq+HI40
'$Vh(-Lf>%V'7O 2'$Vh(-L>774h>21/-/JW72/YP-e>J5Xp[S*;qW.26SHS0C0G>1gW'%a:Zx53)]X;/_Jx(2uY67%((E%t\7\5<)1-5<VI(/Xz:Yq+H'VS)xJW2%ahZbRI>0XI/_3xcI/S\7X((EVML
)5i)/3w'\S,:3js9X0'A[xF9H5+[q;:$)5i)/3wj%-w6B0ghm# %FdD.#/9'kx;v_jX3'*VS$*w'BA:z=-JEuji$,QPh'4288z((e J9<5J:=6 YX+PC2vy(7*;-'bJ9Hv!:]0*5!-H>:42,_3X(/vml
)5i)/3w'X#o):j:x5S2C9Ey)$jF=F12<9zs!mxP/9/#09[ad6%s<cM;[7[;-/b:S$]JC]x;/_jX(2jJ5B*wf)1-pJr!:=6uYX++>sUT(7\5O)1-pBU+((xiv_3XCuUJ\7*k-'bs0J-!:DAHz=U!Y
3js9X0'7/'J$)5i)/3wj%-w72/yp-E*(9-u/6CV:\0u.4tw+k;g36zsU5>2GyQ+h/Uy;i-T:50*p!jH)'%J67%((e1)0R# ;BA:zXvLM$*288d((e1J(Xj,:]p*7!-3M'4269Quh:v)5R#m-[bH(R8
o):j:x54P:3js9X0' X 2:,9;<y2Z$+zkQw.2<9zs!mxZ[//=QBdoGs#$O)1-pJ5,W'$2G9Q+h/jy5B-T:RA:zX;4r9[3/_jX(:h)(i# ;%A:zX-J(/f26yQPh'U)5R#T<)%-)<;ur9C*7!3Jr6
eY)$Jf=3 _574h>21/-%sp:YipV9')+9-U/6cv:\0U.4TW+K;G36ZSu5>2gYq+H/uY;I-t:50*P!Jh)'%j67%((E1)0r# ;ba:ZxVlm$*288D((E1j(xJ,:]P*7!-3m'4269qUH:V)5r#M-[Bh(r8
o):j:x54u=3MZ$)5i)/3wdX#5f\pu:0\w6B0ghm#y<Bd7W7\/AcIg/6K$%9= YX++C:U)*.#$<)1-pBv3Ms$23_jX(uvm$#'k-/bHS=5uE9[3v_jX3u y5>#TO)1-;i;ur9$uYX+,Wu%m$uQ+h:Uml
)5i)/3w'BEoU]lF>=#o):j:x5h+:yIPv9')+9-a[6CV:\>a.4tw2k;g36zsU5>2GyQ+h/1e;=YT:50*p!ju($f)67%((e1)0R# ;BA:z=j,Esv288d((e1+5H3i:]p*p!vL(24269Q+h(j+9R#m-/bsS<$q
72/YP-eOcQeO65493l%2'$Vh(-L>P7'=6%03T##Y%KD7w79/%C8d$.g*qrDU.\[/:5P*P!J+#( v67[K-/B:5xu,m]Xlyx++mI4288Z((E :;>y4:=6 yx++P'/h)7*;-/BS*x5!:]0*P!]hP242,_Jx>UVML
)5i)/3w'JEoU=lF>#[w72/yp-E C9;Dj9G\ [xP/9\s!mxP/9/#09[ad6ts<cM;[7[;-/b:S=3T:50*p!jHM2$23_jXC$4288z((e%+)Hj+:=6 YX+PC:/:p7*;-/by5Hv!:]0*7!-4>:42,_jXp0z
F9H5+[qE)-)K =3MZx74H>21/-#-w72/yp-E*C9-u/#/#09-u/6CV:=>>.m/kQo=a$1d((e1)7=*w'BA:zX53)]xLYX+uW0xZ:9Q+h'vs)Xjw+yp*p!3u>:1:$.d((ejJ)H$w2BAHzBri>0x4YX+4r6
eY)$Jf=3uW'\*'7O$;-)kp:3JS9x0'7ULf>.e (9;dJ9g\ [Xp[S*;qW.2<SgtoC8d$.g*qMDU.\[/:5P*P!J,mU$2g9q+H[1t*$]t:ra:Zbu!:=6Uyx++>$FS57\5o)1-Ph3I)$XIV_3x)'/S\7*K-[Bv(<V3R9c*7!R!y
3js9X0'7ulF>.EoU]3w'\3w72/yp-E C9Ey)$jF=F%2'$vH(-lFS5492q[:$+G/2%d7W7*/Ac.g/6K$%9= YX+P#/hi$1z((e1eSJ*wf)1-5i$w+y0*p!ji3:jT$#';-/b:*HY+(9$ YJ+up:/m$.z(3ejJ)H$wI) -0R8
q
H0[I:MsQ
.UNPROT
.ENDS
