transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -vlog01compat -work work +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/fpga_debug {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/fpga_debug/write_axi.v}
vlog -vlog01compat -work work +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/fpga_debug {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/fpga_debug/debounce.v}
vlog -vlog01compat -work work +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/fpga_debug {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/fpga_debug/clock_reduce.v}
vlog -vlog01compat -work work +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/RTL_VB {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/RTL_VB/fsm_spw.v}
vlog -vlog01compat -work work +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/RTL_VB {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/RTL_VB/rx_spw.v}
vlog -vlog01compat -work work +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/RTL_VB {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/RTL_VB/tx_spw.v}
vlog -vlog01compat -work work +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/rtl_top {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/rtl_top/spw_ulight_con.v}
vlog -vlog01compat -work work +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/fpga_debug {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/rtl/fpga_debug/detector_tokens.v}
vlib spw_ulight_nofifo
vmap spw_ulight_nofifo spw_ulight_nofifo
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/spw_ulight_nofifo.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_timec_tx_to_w.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_timec_rx_r.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_pll_tx.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_led_fpga.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_hps_0.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_hps_0_hps_io.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_clock_pair_generator.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_acv_hard_addr_cmd_pads.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_acv_hard_memphy.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_acv_ldc.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_acv_hard_io_pads.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_generic_ddio.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0_altdqdqs.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_mem_if_hhp_qseq_synth_top.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_fsm_info.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_data_tx_to_w.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_data_rx_ready_0.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_data_rx_r.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_clock_sel.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_auto_start.v}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_MONITOR_A.v}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_burst_adapter_13_1.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_address_alignment.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_traffic_limiter.sv}
vlog -vlog01compat -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_router_002.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_mm_interconnect_0_router.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_axi_master_ni.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_pll.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/hps_sdram_p0.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altdq_dqs2_acv_connect_to_hard_phy_cyclonev.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_mem_if_hard_memory_controller_top_cyclonev.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_mem_if_oct_cyclonev.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/altera_mem_if_dll_cyclonev.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_hps_0_hps_io_border.sv}
vlog -sv -work spw_ulight_nofifo +incdir+/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules {/home/felipe/Documentos/verilog_projects/SPW_SC/TESTSTRESS/altera_fpga_de0_nano/spw_ulight_nofifo/synthesis/submodules/spw_ulight_nofifo_hps_0_fpga_interfaces.sv}

