	spw_light u0 (
		.autostart_external_connection_export  (<connected-to-autostart_external_connection_export>),  //  autostart_external_connection.export
		.clk_clk                               (<connected-to-clk_clk>),                               //                            clk.clk
		.connecting_external_connection_export (<connected-to-connecting_external_connection_export>), // connecting_external_connection.export
		.ctrl_in_external_connection_export    (<connected-to-ctrl_in_external_connection_export>),    //    ctrl_in_external_connection.export
		.ctrl_out_external_connection_export   (<connected-to-ctrl_out_external_connection_export>),   //   ctrl_out_external_connection.export
		.errcred_external_connection_export    (<connected-to-errcred_external_connection_export>),    //    errcred_external_connection.export
		.errdisc_external_connection_export    (<connected-to-errdisc_external_connection_export>),    //    errdisc_external_connection.export
		.erresc_external_connection_export     (<connected-to-erresc_external_connection_export>),     //     erresc_external_connection.export
		.errpar_external_connection_export     (<connected-to-errpar_external_connection_export>),     //     errpar_external_connection.export
		.linkdis_external_connection_export    (<connected-to-linkdis_external_connection_export>),    //    linkdis_external_connection.export
		.linkstart_external_connection_export  (<connected-to-linkstart_external_connection_export>),  //  linkstart_external_connection.export
		.memory_mem_a                          (<connected-to-memory_mem_a>),                          //                         memory.mem_a
		.memory_mem_ba                         (<connected-to-memory_mem_ba>),                         //                               .mem_ba
		.memory_mem_ck                         (<connected-to-memory_mem_ck>),                         //                               .mem_ck
		.memory_mem_ck_n                       (<connected-to-memory_mem_ck_n>),                       //                               .mem_ck_n
		.memory_mem_cke                        (<connected-to-memory_mem_cke>),                        //                               .mem_cke
		.memory_mem_cs_n                       (<connected-to-memory_mem_cs_n>),                       //                               .mem_cs_n
		.memory_mem_ras_n                      (<connected-to-memory_mem_ras_n>),                      //                               .mem_ras_n
		.memory_mem_cas_n                      (<connected-to-memory_mem_cas_n>),                      //                               .mem_cas_n
		.memory_mem_we_n                       (<connected-to-memory_mem_we_n>),                       //                               .mem_we_n
		.memory_mem_reset_n                    (<connected-to-memory_mem_reset_n>),                    //                               .mem_reset_n
		.memory_mem_dq                         (<connected-to-memory_mem_dq>),                         //                               .mem_dq
		.memory_mem_dqs                        (<connected-to-memory_mem_dqs>),                        //                               .mem_dqs
		.memory_mem_dqs_n                      (<connected-to-memory_mem_dqs_n>),                      //                               .mem_dqs_n
		.memory_mem_odt                        (<connected-to-memory_mem_odt>),                        //                               .mem_odt
		.memory_mem_dm                         (<connected-to-memory_mem_dm>),                         //                               .mem_dm
		.memory_oct_rzqin                      (<connected-to-memory_oct_rzqin>),                      //                               .oct_rzqin
		.pll_0_locked_export                   (<connected-to-pll_0_locked_export>),                   //                   pll_0_locked.export
		.pll_0_outclk0_clk                     (<connected-to-pll_0_outclk0_clk>),                     //                  pll_0_outclk0.clk
		.reset_reset_n                         (<connected-to-reset_reset_n>),                         //                          reset.reset_n
		.running_external_connection_export    (<connected-to-running_external_connection_export>),    //    running_external_connection.export
		.rxdata_external_connection_export     (<connected-to-rxdata_external_connection_export>),     //     rxdata_external_connection.export
		.rxflag_external_connection_export     (<connected-to-rxflag_external_connection_export>),     //     rxflag_external_connection.export
		.rxhalff_external_connection_export    (<connected-to-rxhalff_external_connection_export>),    //    rxhalff_external_connection.export
		.rxread_external_connection_export     (<connected-to-rxread_external_connection_export>),     //     rxread_external_connection.export
		.rxvalid_external_connection_export    (<connected-to-rxvalid_external_connection_export>),    //    rxvalid_external_connection.export
		.started_external_connection_export    (<connected-to-started_external_connection_export>),    //    started_external_connection.export
		.tick_in_external_connection_export    (<connected-to-tick_in_external_connection_export>),    //    tick_in_external_connection.export
		.tick_out_external_connection_export   (<connected-to-tick_out_external_connection_export>),   //   tick_out_external_connection.export
		.time_in_external_connection_export    (<connected-to-time_in_external_connection_export>),    //    time_in_external_connection.export
		.time_out_external_connection_export   (<connected-to-time_out_external_connection_export>),   //   time_out_external_connection.export
		.txdata_external_connection_export     (<connected-to-txdata_external_connection_export>),     //     txdata_external_connection.export
		.txdivcnt_external_connection_export   (<connected-to-txdivcnt_external_connection_export>),   //   txdivcnt_external_connection.export
		.txflag_external_connection_export     (<connected-to-txflag_external_connection_export>),     //     txflag_external_connection.export
		.txhalff_external_connection_export    (<connected-to-txhalff_external_connection_export>),    //    txhalff_external_connection.export
		.txrdy_external_connection_export      (<connected-to-txrdy_external_connection_export>),      //      txrdy_external_connection.export
		.txwrite_external_connection_export    (<connected-to-txwrite_external_connection_export>)     //    txwrite_external_connection.export
	);

