	jaxa u0 (
		.autostart_external_connection_export                   (<connected-to-autostart_external_connection_export>),                   //                   autostart_external_connection.export
		.clk_clk                                                (<connected-to-clk_clk>),                                                //                                             clk.clk
		.controlflagsin_external_connection_export              (<connected-to-controlflagsin_external_connection_export>),              //              controlflagsin_external_connection.export
		.controlflagsout_external_connection_export             (<connected-to-controlflagsout_external_connection_export>),             //             controlflagsout_external_connection.export
		.creditcount_external_connection_export                 (<connected-to-creditcount_external_connection_export>),                 //                 creditcount_external_connection.export
		.errorstatus_external_connection_export                 (<connected-to-errorstatus_external_connection_export>),                 //                 errorstatus_external_connection.export
		.linkdisable_external_connection_export                 (<connected-to-linkdisable_external_connection_export>),                 //                 linkdisable_external_connection.export
		.linkstart_external_connection_export                   (<connected-to-linkstart_external_connection_export>),                   //                   linkstart_external_connection.export
		.linkstatus_external_connection_export                  (<connected-to-linkstatus_external_connection_export>),                  //                  linkstatus_external_connection.export
		.memory_mem_a                                           (<connected-to-memory_mem_a>),                                           //                                          memory.mem_a
		.memory_mem_ba                                          (<connected-to-memory_mem_ba>),                                          //                                                .mem_ba
		.memory_mem_ck                                          (<connected-to-memory_mem_ck>),                                          //                                                .mem_ck
		.memory_mem_ck_n                                        (<connected-to-memory_mem_ck_n>),                                        //                                                .mem_ck_n
		.memory_mem_cke                                         (<connected-to-memory_mem_cke>),                                         //                                                .mem_cke
		.memory_mem_cs_n                                        (<connected-to-memory_mem_cs_n>),                                        //                                                .mem_cs_n
		.memory_mem_ras_n                                       (<connected-to-memory_mem_ras_n>),                                       //                                                .mem_ras_n
		.memory_mem_cas_n                                       (<connected-to-memory_mem_cas_n>),                                       //                                                .mem_cas_n
		.memory_mem_we_n                                        (<connected-to-memory_mem_we_n>),                                        //                                                .mem_we_n
		.memory_mem_reset_n                                     (<connected-to-memory_mem_reset_n>),                                     //                                                .mem_reset_n
		.memory_mem_dq                                          (<connected-to-memory_mem_dq>),                                          //                                                .mem_dq
		.memory_mem_dqs                                         (<connected-to-memory_mem_dqs>),                                         //                                                .mem_dqs
		.memory_mem_dqs_n                                       (<connected-to-memory_mem_dqs_n>),                                       //                                                .mem_dqs_n
		.memory_mem_odt                                         (<connected-to-memory_mem_odt>),                                         //                                                .mem_odt
		.memory_mem_dm                                          (<connected-to-memory_mem_dm>),                                          //                                                .mem_dm
		.memory_oct_rzqin                                       (<connected-to-memory_oct_rzqin>),                                       //                                                .oct_rzqin
		.outstandingcount_external_connection_export            (<connected-to-outstandingcount_external_connection_export>),            //            outstandingcount_external_connection.export
		.pll_0_outclk0_clk                                      (<connected-to-pll_0_outclk0_clk>),                                      //                                   pll_0_outclk0.clk
		.receiveactivity_external_connection_export             (<connected-to-receiveactivity_external_connection_export>),             //             receiveactivity_external_connection.export
		.receiveclock_external_connection_export                (<connected-to-receiveclock_external_connection_export>),                //                receiveclock_external_connection.export
		.receivefifodatacount_external_connection_export        (<connected-to-receivefifodatacount_external_connection_export>),        //        receivefifodatacount_external_connection.export
		.receivefifodataout_external_connection_export          (<connected-to-receivefifodataout_external_connection_export>),          //          receivefifodataout_external_connection.export
		.receivefifoempty_external_connection_export            (<connected-to-receivefifoempty_external_connection_export>),            //            receivefifoempty_external_connection.export
		.receivefifofull_external_connection_export             (<connected-to-receivefifofull_external_connection_export>),             //             receivefifofull_external_connection.export
		.receivefiforeadenable_external_connection_export       (<connected-to-receivefiforeadenable_external_connection_export>),       //       receivefiforeadenable_external_connection.export
		.spacewiredatain_external_connection_export             (<connected-to-spacewiredatain_external_connection_export>),             //             spacewiredatain_external_connection.export
		.spacewiredataout_external_connection_export            (<connected-to-spacewiredataout_external_connection_export>),            //            spacewiredataout_external_connection.export
		.spacewirestrobein_external_connection_export           (<connected-to-spacewirestrobein_external_connection_export>),           //           spacewirestrobein_external_connection.export
		.spacewirestrobeout_external_connection_export          (<connected-to-spacewirestrobeout_external_connection_export>),          //          spacewirestrobeout_external_connection.export
		.statisticalinformation_0_external_connection_export    (<connected-to-statisticalinformation_0_external_connection_export>),    //    statisticalinformation_0_external_connection.export
		.statisticalinformation_1_external_connection_export    (<connected-to-statisticalinformation_1_external_connection_export>),    //    statisticalinformation_1_external_connection.export
		.statisticalinformationclear_external_connection_export (<connected-to-statisticalinformationclear_external_connection_export>), // statisticalinformationclear_external_connection.export
		.tickin_external_connection_export                      (<connected-to-tickin_external_connection_export>),                      //                      tickin_external_connection.export
		.tickout_external_connection_export                     (<connected-to-tickout_external_connection_export>),                     //                     tickout_external_connection.export
		.timein_external_connection_export                      (<connected-to-timein_external_connection_export>),                      //                      timein_external_connection.export
		.timeout_external_connection_export                     (<connected-to-timeout_external_connection_export>),                     //                     timeout_external_connection.export
		.transmitactivity_external_connection_export            (<connected-to-transmitactivity_external_connection_export>),            //            transmitactivity_external_connection.export
		.transmitclock_external_connection_export               (<connected-to-transmitclock_external_connection_export>),               //               transmitclock_external_connection.export
		.transmitclockdividevalue_external_connection_export    (<connected-to-transmitclockdividevalue_external_connection_export>),    //    transmitclockdividevalue_external_connection.export
		.transmitfifodatacount_external_connection_export       (<connected-to-transmitfifodatacount_external_connection_export>),       //       transmitfifodatacount_external_connection.export
		.transmitfifodatain_external_connection_export          (<connected-to-transmitfifodatain_external_connection_export>),          //          transmitfifodatain_external_connection.export
		.transmitfifofull_external_connection_export            (<connected-to-transmitfifofull_external_connection_export>),            //            transmitfifofull_external_connection.export
		.transmitfifowriteenable_external_connection_export     (<connected-to-transmitfifowriteenable_external_connection_export>)      //     transmitfifowriteenable_external_connection.export
	);

